.TH "arithmetic" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arithmetic
.SH SYNOPSIS
.br
.PP
.SH "Concept definition"
.PP 
.PP
.nf
template<typename T>
concept arithmetic =  std::is_arithmetic_v<T>
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
