.TH "Controllable" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controllable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBComponent\fP, and \fBObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBbase_clean_up\fP ()"
.br
.ti -1c
.RI "virtual void \fBbase_compile\fP ()"
.br
.ti -1c
.RI "virtual void \fBbase_tick\fP (float dt)"
.br
.ti -1c
.RI "virtual void \fBon_start\fP ()"
.br
.ti -1c
.RI "virtual void \fBclean_up\fP ()"
.br
.ti -1c
.RI "virtual void \fBcompile\fP ()"
.br
.ti -1c
.RI "virtual void \fBtick\fP (float dt)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
