.TH "DDS_HEADER_DXT10" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DDS_HEADER_DXT10
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DXGI_FORMAT \fBdxgiFormat\fP"
.br
.ti -1c
.RI "uint32_t \fBresourceDimension\fP"
.br
.ti -1c
.RI "uint32_t \fBmiscFlag\fP"
.br
.ti -1c
.RI "uint32_t \fBarraySize\fP"
.br
.ti -1c
.RI "uint32_t \fBmiscFlags2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
