.TH "DDS_PIXELFORMAT" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DDS_PIXELFORMAT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "uint32_t \fBfourCC\fP"
.br
.ti -1c
.RI "uint32_t \fBRGBBitCount\fP"
.br
.ti -1c
.RI "uint32_t \fBRBitMask\fP"
.br
.ti -1c
.RI "uint32_t \fBGBitMask\fP"
.br
.ti -1c
.RI "uint32_t \fBBBitMask\fP"
.br
.ti -1c
.RI "uint32_t \fBABitMask\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
