.TH "DirectX::HDRColorA" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::HDRColorA
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDRColorA\fP (float _r, float _g, float _b, float _a) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP (const \fBHDRColorA\fP &c) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP \fBoperator+\fP (const \fBHDRColorA\fP &c) const noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP \fBoperator\-\fP (const \fBHDRColorA\fP &c) const noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP \fBoperator*\fP (float f) const noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP \fBoperator/\fP (float f) const noexcept"
.br
.ti -1c
.RI "float \fBoperator*\fP (const \fBHDRColorA\fP &c) const noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP & \fBoperator+=\fP (const \fBHDRColorA\fP &c) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP & \fBoperator\-=\fP (const \fBHDRColorA\fP &c) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP & \fBoperator*=\fP (float f) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP & \fBoperator/=\fP (float f) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP & \fBClamp\fP (_In_ float fMin, _In_ float fMax) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP (const \fBLDRColorA\fP &c) noexcept"
.br
.ti -1c
.RI "\fBHDRColorA\fP & \fBoperator=\fP (const \fBLDRColorA\fP &c) noexcept"
.br
.ti -1c
.RI "\fBLDRColorA\fP \fBToLDRColorA\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBg\fP"
.br
.ti -1c
.RI "float \fBb\fP"
.br
.ti -1c
.RI "float \fBa\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
