.TH "DirectX::LDREndPntPair" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::LDREndPntPair
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLDRColorA\fP \fBA\fP"
.br
.ti -1c
.RI "\fBLDRColorA\fP \fBB\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
