.TH "DirectX::Filters::TriangleRow" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::Filters::TriangleRow
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBremaining\fP"
.br
.ti -1c
.RI "\fBTriangleRow\fP * \fBnext\fP"
.br
.ti -1c
.RI "ScopedAlignedArrayXMVECTOR \fBscanline\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
