.TH "DirectX::SharedResourcePool< TKey, TData, TConstructorArgs >" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::SharedResourcePool< TKey, TData, TConstructorArgs >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSharedResourcePool\fP (\fBSharedResourcePool\fP const &)=delete"
.br
.ti -1c
.RI "\fBSharedResourcePool\fP & \fBoperator=\fP (\fBSharedResourcePool\fP const &)=delete"
.br
.ti -1c
.RI "std::shared_ptr< TData > \fBDemandCreate\fP (TKey key, TConstructorArgs\&.\&.\&. args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
