.TH "DirectX::Mouse::State" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::Mouse::State
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBleftButton\fP"
.br
.ti -1c
.RI "bool \fBmiddleButton\fP"
.br
.ti -1c
.RI "bool \fBrightButton\fP"
.br
.ti -1c
.RI "bool \fBxButton1\fP"
.br
.ti -1c
.RI "bool \fBxButton2\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBscrollWheelValue\fP"
.br
.ti -1c
.RI "Mode \fBpositionMode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
