.TH "DirectX::DDS_HEADER" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::DDS_HEADER
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "uint32_t \fBheight\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth\fP"
.br
.ti -1c
.RI "uint32_t \fBpitchOrLinearSize\fP"
.br
.ti -1c
.RI "uint32_t \fBdepth\fP"
.br
.ti -1c
.RI "uint32_t \fBmipMapCount\fP"
.br
.ti -1c
.RI "uint32_t \fBreserved1\fP [11]"
.br
.ti -1c
.RI "\fBDDS_PIXELFORMAT\fP \fBddspf\fP"
.br
.ti -1c
.RI "uint32_t \fBcaps\fP"
.br
.ti -1c
.RI "uint32_t \fBcaps2\fP"
.br
.ti -1c
.RI "uint32_t \fBcaps3\fP"
.br
.ti -1c
.RI "uint32_t \fBcaps4\fP"
.br
.ti -1c
.RI "uint32_t \fBreserved2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
