.TH "DirectX::Filters::CubicFilter" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::Filters::CubicFilter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBu0\fP"
.br
.ti -1c
.RI "size_t \fBu1\fP"
.br
.ti -1c
.RI "size_t \fBu2\fP"
.br
.ti -1c
.RI "size_t \fBu3\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
