.TH "DirectX::Filters::FilterFrom" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::Filters::FilterFrom
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBsizeInBytes\fP"
.br
.ti -1c
.RI "\fBFilterTo\fP \fBto\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
