.TH "DirectX::DualPostProcess" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::DualPostProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDirectX::IPostProcess\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImpl\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEffect\fP : unsigned int { \fBMerge\fP, \fBBloomCombine\fP, \fBEffect_Max\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDualPostProcess\fP (_In_ ID3D11Device *device)"
.br
.ti -1c
.RI "\fBDualPostProcess\fP (\fBDualPostProcess\fP &&) noexcept"
.br
.ti -1c
.RI "\fBDualPostProcess\fP & \fBoperator=\fP (\fBDualPostProcess\fP &&) noexcept"
.br
.ti -1c
.RI "\fBDualPostProcess\fP (\fBDualPostProcess\fP const &)=delete"
.br
.ti -1c
.RI "\fBDualPostProcess\fP & \fBoperator=\fP (\fBDualPostProcess\fP const &)=delete"
.br
.ti -1c
.RI "void __cdecl \fBProcess\fP (_In_ ID3D11DeviceContext *deviceContext, _In_opt_ std::function< void __cdecl()> setCustomState=nullptr) override"
.br
.ti -1c
.RI "void __cdecl \fBSetEffect\fP (Effect fx)"
.br
.ti -1c
.RI "void __cdecl \fBSetSourceTexture\fP (_In_opt_ ID3D11ShaderResourceView *value)"
.br
.ti -1c
.RI "void __cdecl \fBSetSourceTexture2\fP (_In_opt_ ID3D11ShaderResourceView *value)"
.br
.ti -1c
.RI "void __cdecl \fBSetMergeParameters\fP (float weight1, float weight2)"
.br
.ti -1c
.RI "void __cdecl \fBSetBloomCombineParameters\fP (float bloom, float base, float bloomSaturation, float baseSaturation)"
.br
.in -1c

Public Member Functions inherited from \fBDirectX::IPostProcess\fP
.in +1c
.ti -1c
.RI "\fBIPostProcess\fP (const \fBIPostProcess\fP &)=delete"
.br
.ti -1c
.RI "\fBIPostProcess\fP & \fBoperator=\fP (const \fBIPostProcess\fP &)=delete"
.br
.ti -1c
.RI "virtual void __cdecl \fBProcess\fP (_In_ ID3D11DeviceContext *deviceContext, _In_opt_ std::function< void __cdecl()> setCustomState=nullptr)=0"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBDirectX::IPostProcess\fP
.in +1c
.ti -1c
.RI "\fBIPostProcess\fP (\fBIPostProcess\fP &&)=default"
.br
.ti -1c
.RI "\fBIPostProcess\fP & \fBoperator=\fP (\fBIPostProcess\fP &&)=default"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void DualPostProcess::Process (_In_ ID3D11DeviceContext * deviceContext, _In_opt_ std::function< void __cdecl()> setCustomState = \fCnullptr\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBDirectX::IPostProcess\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
