.TH "DirectX::GamePad::Buttons" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::GamePad::Buttons
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBa\fP"
.br
.ti -1c
.RI "bool \fBb\fP"
.br
.ti -1c
.RI "bool \fBx\fP"
.br
.ti -1c
.RI "bool \fBy\fP"
.br
.ti -1c
.RI "bool \fBleftStick\fP"
.br
.ti -1c
.RI "bool \fBrightStick\fP"
.br
.ti -1c
.RI "bool \fBleftShoulder\fP"
.br
.ti -1c
.RI "bool \fBrightShoulder\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   bool \fBback\fP"
.br
.ti -1c
.RI "   bool \fBview\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   bool \fBstart\fP"
.br
.ti -1c
.RI "   bool \fBmenu\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
