.TH "DirectX::AudioStatistics" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::AudioStatistics
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBplayingOneShots\fP"
.br
.ti -1c
.RI "size_t \fBplayingInstances\fP"
.br
.ti -1c
.RI "size_t \fBallocatedInstances\fP"
.br
.ti -1c
.RI "size_t \fBallocatedVoices\fP"
.br
.ti -1c
.RI "size_t \fBallocatedVoices3d\fP"
.br
.ti -1c
.RI "size_t \fBallocatedVoicesOneShot\fP"
.br
.ti -1c
.RI "size_t \fBallocatedVoicesIdle\fP"
.br
.ti -1c
.RI "size_t \fBaudioBytes\fP"
.br
.ti -1c
.RI "size_t \fBstreamingBytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
