.TH "DirectX::GamePad::DPad" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::GamePad::DPad
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBup\fP"
.br
.ti -1c
.RI "bool \fBdown\fP"
.br
.ti -1c
.RI "bool \fBright\fP"
.br
.ti -1c
.RI "bool \fBleft\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
