.TH "DirectX::EffectColor" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::EffectColor
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDirectX::EffectLights\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetConstants\fP (_Inout_ int &dirtyFlags, _Inout_ XMVECTOR &diffuseColorConstant)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "XMVECTOR \fBdiffuseColor\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
