.TH "DirectX::IEffectFactory::EffectInfo" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::IEffectFactory::EffectInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDirectX::DGSLEffectFactory::DGSLEffectInfo\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const wchar_t * \fBname\fP"
.br
.ti -1c
.RI "bool \fBperVertexColor\fP"
.br
.ti -1c
.RI "bool \fBenableSkinning\fP"
.br
.ti -1c
.RI "bool \fBenableDualTexture\fP"
.br
.ti -1c
.RI "bool \fBenableNormalMaps\fP"
.br
.ti -1c
.RI "bool \fBbiasedVertexNormals\fP"
.br
.ti -1c
.RI "float \fBspecularPower\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBambientColor\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBdiffuseColor\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBspecularColor\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBemissiveColor\fP"
.br
.ti -1c
.RI "const wchar_t * \fBdiffuseTexture\fP"
.br
.ti -1c
.RI "const wchar_t * \fBspecularTexture\fP"
.br
.ti -1c
.RI "const wchar_t * \fBnormalTexture\fP"
.br
.ti -1c
.RI "const wchar_t * \fBemissiveTexture\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
