.TH "DirectX::DGSLEffectFactory::DGSLEffectInfo" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::DGSLEffectFactory::DGSLEffectInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDirectX::IEffectFactory::EffectInfo\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const wchar_t * \fBtextures\fP [DGSLEffect::MaxTextures \- BaseTextureOffset]"
.br
.ti -1c
.RI "const wchar_t * \fBpixelShader\fP"
.br
.in -1c

Public Attributes inherited from \fBDirectX::IEffectFactory::EffectInfo\fP
.in +1c
.ti -1c
.RI "const wchar_t * \fBname\fP"
.br
.ti -1c
.RI "bool \fBperVertexColor\fP"
.br
.ti -1c
.RI "bool \fBenableSkinning\fP"
.br
.ti -1c
.RI "bool \fBenableDualTexture\fP"
.br
.ti -1c
.RI "bool \fBenableNormalMaps\fP"
.br
.ti -1c
.RI "bool \fBbiasedVertexNormals\fP"
.br
.ti -1c
.RI "float \fBspecularPower\fP"
.br
.ti -1c
.RI "float \fBalpha\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBambientColor\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBdiffuseColor\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBspecularColor\fP"
.br
.ti -1c
.RI "XMFLOAT3 \fBemissiveColor\fP"
.br
.ti -1c
.RI "const wchar_t * \fBdiffuseTexture\fP"
.br
.ti -1c
.RI "const wchar_t * \fBspecularTexture\fP"
.br
.ti -1c
.RI "const wchar_t * \fBnormalTexture\fP"
.br
.ti -1c
.RI "const wchar_t * \fBemissiveTexture\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBBaseTextureOffset\fP = 4"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
