.TH "DirectionalLightComponent::DLData" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectionalLightComponent::DLData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFVector3\fP \fBdirection\fP = \fBFVector3\fP(0\&.25f, 0\&.5f, \-1\&.0f)"
.br
.ti -1c
.RI "\fBColor\fP \fBdiffuse\fP = \fBColor\fP(100, 100, 100, 100)"
.br
.ti -1c
.RI "\fBColor\fP \fBspecular\fP = \fBColor\fP(0, 0, 0, 255)"
.br
.ti -1c
.RI "bool \fBnull\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
