.TH "DirectX::GamePad::State" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::GamePad::State
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool __cdecl \fBIsConnected\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsAPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsBPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsXPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsYPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsLeftStickPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsRightStickPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsLeftShoulderPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsRightShoulderPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsBackPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsViewPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsStartPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsMenuPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsDPadDownPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsDPadUpPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsDPadLeftPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsDPadRightPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsLeftThumbStickUp\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsLeftThumbStickDown\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsLeftThumbStickLeft\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsLeftThumbStickRight\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsRightThumbStickUp\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsRightThumbStickDown\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsRightThumbStickLeft\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsRightThumbStickRight\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsLeftTriggerPressed\fP () const noexcept"
.br
.ti -1c
.RI "bool __cdecl \fBIsRightTriggerPressed\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBconnected\fP"
.br
.ti -1c
.RI "uint64_t \fBpacket\fP"
.br
.ti -1c
.RI "\fBButtons\fP \fBbuttons\fP"
.br
.ti -1c
.RI "\fBDPad\fP \fBdpad\fP"
.br
.ti -1c
.RI "\fBThumbSticks\fP \fBthumbSticks\fP"
.br
.ti -1c
.RI "\fBTriggers\fP \fBtriggers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
