.TH "DirectX::GamePad::Capabilities" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::GamePad::Capabilities
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBUNKNOWN\fP = 0, \fBGAMEPAD\fP, \fBWHEEL\fP, \fBARCADE_STICK\fP, \fBFLIGHT_STICK\fP, \fBDANCE_PAD\fP, \fBGUITAR\fP, \fBGUITAR_ALTERNATE\fP, \fBDRUM_KIT\fP, \fBGUITAR_BASS\fP = 11, \fBARCADE_PAD\fP = 19 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool __cdecl \fBIsConnected\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBconnected\fP"
.br
.ti -1c
.RI "Type \fBgamepadType\fP"
.br
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "uint16_t \fBvid\fP"
.br
.ti -1c
.RI "uint16_t \fBpid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
