.TH "DirectX::EffectFog" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::EffectFog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void XM_CALLCONV \fBSetConstants\fP (_Inout_ int &dirtyFlags, _In_ FXMMATRIX worldView, _Inout_ XMVECTOR &fogVectorConstant)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBenabled\fP"
.br
.ti -1c
.RI "float \fBstart\fP"
.br
.ti -1c
.RI "float \fBend\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
