.TH "DirectX::AlignedNew< TDerived >" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::AlignedNew< TDerived >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBoperator new\fP (size_t size)"
.br
.ti -1c
.RI "static void \fBoperator delete\fP (void *ptr)"
.br
.ti -1c
.RI "static void * \fBoperator new[]\fP (size_t size)"
.br
.ti -1c
.RI "static void \fBoperator delete[]\fP (void *ptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
