.TH "DirectX::D3DX_BC3" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::D3DX_BC3
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBalpha\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBbitmap\fP [6]"
.br
.ti -1c
.RI "\fBD3DX_BC1\fP \fBbc1\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
