.TH "DirectX::Internal::ConstantBufferBase" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::Internal::ConstantBufferBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDirectX::ConstantBuffer< typename Traits::ConstantBufferType >\fP, \fBDirectX::ConstantBuffer< PostProcessConstants >\fP, \fBDirectX::ConstantBuffer< MaterialConstants >\fP, \fBDirectX::ConstantBuffer< LightConstants >\fP, \fBDirectX::ConstantBuffer< ObjectConstants >\fP, \fBDirectX::ConstantBuffer< MiscConstants >\fP, \fBDirectX::ConstantBuffer< BoneConstants >\fP, \fBDirectX::ConstantBuffer< ToneMapConstants >\fP, and \fBDirectX::ConstantBuffer< T >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void __cdecl \fBCreateBuffer\fP (_In_ ID3D11Device *device, size_t bytes, _Outptr_ ID3D11Buffer **pBuffer)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
