.TH "DirectX::WAVData" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::WAVData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const WAVEFORMATEX * \fBwfx\fP"
.br
.ti -1c
.RI "const uint8_t * \fBstartAudio\fP"
.br
.ti -1c
.RI "uint32_t \fBaudioBytes\fP"
.br
.ti -1c
.RI "uint32_t \fBloopStart\fP"
.br
.ti -1c
.RI "uint32_t \fBloopLength\fP"
.br
.ti -1c
.RI "const uint32_t * \fBseek\fP"
.br
.ti -1c
.RI "uint32_t \fBseekCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
