.TH "DirectX::LoaderHelpers::auto_delete_file" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::LoaderHelpers::auto_delete_file
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauto_delete_file\fP (HANDLE hFile) noexcept"
.br
.ti -1c
.RI "\fBauto_delete_file\fP (const \fBauto_delete_file\fP &)=delete"
.br
.ti -1c
.RI "\fBauto_delete_file\fP & \fBoperator=\fP (const \fBauto_delete_file\fP &)=delete"
.br
.ti -1c
.RI "\fBauto_delete_file\fP (const \fBauto_delete_file\fP &&)=delete"
.br
.ti -1c
.RI "\fBauto_delete_file\fP & \fBoperator=\fP (const \fBauto_delete_file\fP &&)=delete"
.br
.ti -1c
.RI "void \fBclear\fP () noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
