.TH "DirectX::Rect" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::Rect
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRect\fP (size_t _x, size_t _y, size_t _w, size_t _h) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBx\fP"
.br
.ti -1c
.RI "size_t \fBy\fP"
.br
.ti -1c
.RI "size_t \fBw\fP"
.br
.ti -1c
.RI "size_t \fBh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
