.TH "DirectX::EffectBase< Traits >" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::EffectBase< Traits >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDirectX::AlignedNew< Traits::ConstantBufferType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffectBase\fP (_In_ ID3D11Device *device)"
.br
.ti -1c
.RI "\fBEffectBase\fP (\fBEffectBase\fP &&)=default"
.br
.ti -1c
.RI "\fBEffectBase\fP & \fBoperator=\fP (\fBEffectBase\fP &&)=default"
.br
.ti -1c
.RI "\fBEffectBase\fP (\fBEffectBase\fP const &)=delete"
.br
.ti -1c
.RI "\fBEffectBase\fP & \fBoperator=\fP (\fBEffectBase\fP const &)=delete"
.br
.ti -1c
.RI "void \fBGetVertexShaderBytecode\fP (int permutation, _Out_ void const **pShaderByteCode, _Out_ size_t *pByteCodeLength) noexcept"
.br
.ti -1c
.RI "void \fBApplyShaders\fP (_In_ ID3D11DeviceContext *deviceContext, int permutation)"
.br
.ti -1c
.RI "ID3D11ShaderResourceView * \fBGetDefaultTexture\fP ()"
.br
.ti -1c
.RI "ID3D11ShaderResourceView * \fBGetDefaultNormalTexture\fP ()"
.br
.ti -1c
.RI "D3D_FEATURE_LEVEL \fBGetDeviceFeatureLevel\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Traits::ConstantBufferType \fBconstants\fP"
.br
.ti -1c
.RI "\fBEffectMatrices\fP \fBmatrices\fP"
.br
.ti -1c
.RI "\fBEffectFog\fP \fBfog\fP"
.br
.ti -1c
.RI "Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > \fBtexture\fP"
.br
.ti -1c
.RI "int \fBdirtyFlags\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const \fBShaderBytecode\fP \fBVertexShaderBytecode\fP [Traits::VertexShaderCount]"
.br
.ti -1c
.RI "static const \fBShaderBytecode\fP \fBPixelShaderBytecode\fP [Traits::PixelShaderCount]"
.br
.ti -1c
.RI "static const int \fBVertexShaderIndices\fP [Traits::ShaderPermutationCount]"
.br
.ti -1c
.RI "static const int \fBPixelShaderIndices\fP [Traits::ShaderPermutationCount]"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBDirectX::AlignedNew< Traits::ConstantBufferType >\fP
.in +1c
.ti -1c
.RI "static void * \fBoperator new\fP (size_t size)"
.br
.ti -1c
.RI "static void \fBoperator delete\fP (void *ptr)"
.br
.ti -1c
.RI "static void * \fBoperator new[]\fP (size_t size)"
.br
.ti -1c
.RI "static void \fBoperator delete[]\fP (void *ptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
