.TH "DirectX::IEffectFog" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::IEffectFog
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDirectX::AlphaTestEffect\fP, \fBDirectX::BasicEffect\fP, \fBDirectX::DualTextureEffect\fP, \fBDirectX::EnvironmentMapEffect\fP, \fBDirectX::NormalMapEffect\fP, and \fBDirectX::SkinnedEffect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIEffectFog\fP (const \fBIEffectFog\fP &)=delete"
.br
.ti -1c
.RI "\fBIEffectFog\fP & \fBoperator=\fP (const \fBIEffectFog\fP &)=delete"
.br
.ti -1c
.RI "virtual void __cdecl \fBSetFogEnabled\fP (bool value)=0"
.br
.ti -1c
.RI "virtual void __cdecl \fBSetFogStart\fP (float value)=0"
.br
.ti -1c
.RI "virtual void __cdecl \fBSetFogEnd\fP (float value)=0"
.br
.ti -1c
.RI "virtual void XM_CALLCONV \fBSetFogColor\fP (FXMVECTOR value)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBIEffectFog\fP (\fBIEffectFog\fP &&)=default"
.br
.ti -1c
.RI "\fBIEffectFog\fP & \fBoperator=\fP (\fBIEffectFog\fP &&)=default"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
