.TH "DirectX::com_exception" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::com_exception
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcom_exception\fP (HRESULT hr) noexcept"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.ti -1c
.RI "HRESULT \fBget_result\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
