.TH "DirectX::SpriteFont::Glyph" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::SpriteFont::Glyph
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBCharacter\fP"
.br
.ti -1c
.RI "RECT \fBSubrect\fP"
.br
.ti -1c
.RI "float \fBXOffset\fP"
.br
.ti -1c
.RI "float \fBYOffset\fP"
.br
.ti -1c
.RI "float \fBXAdvance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
