.TH "DirectX::AudioEngine::RendererDetail" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::AudioEngine::RendererDetail
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::wstring \fBdeviceId\fP"
.br
.ti -1c
.RI "std::wstring \fBdescription\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
