.TH "DXUT::D3DVERTEXELEMENT9" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::D3DVERTEXELEMENT9
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBStream\fP"
.br
.ti -1c
.RI "uint16_t \fBOffset\fP"
.br
.ti -1c
.RI "uint8_t \fBType\fP"
.br
.ti -1c
.RI "uint8_t \fBMethod\fP"
.br
.ti -1c
.RI "uint8_t \fBUsage\fP"
.br
.ti -1c
.RI "uint8_t \fBUsageIndex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
