.TH "DXUT::SDKMESH_FRAME" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::SDKMESH_FRAME
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBName\fP [MAX_FRAME_NAME]"
.br
.ti -1c
.RI "uint32_t \fBMesh\fP"
.br
.ti -1c
.RI "uint32_t \fBParentFrame\fP"
.br
.ti -1c
.RI "uint32_t \fBChildFrame\fP"
.br
.ti -1c
.RI "uint32_t \fBSiblingFrame\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBMatrix\fP"
.br
.ti -1c
.RI "uint32_t \fBAnimationDataIndex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
