.TH "DXUT::SDKMESH_HEADER" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::SDKMESH_HEADER
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBVersion\fP"
.br
.ti -1c
.RI "uint8_t \fBIsBigEndian\fP"
.br
.ti -1c
.RI "uint64_t \fBHeaderSize\fP"
.br
.ti -1c
.RI "uint64_t \fBNonBufferDataSize\fP"
.br
.ti -1c
.RI "uint64_t \fBBufferDataSize\fP"
.br
.ti -1c
.RI "uint32_t \fBNumVertexBuffers\fP"
.br
.ti -1c
.RI "uint32_t \fBNumIndexBuffers\fP"
.br
.ti -1c
.RI "uint32_t \fBNumMeshes\fP"
.br
.ti -1c
.RI "uint32_t \fBNumTotalSubsets\fP"
.br
.ti -1c
.RI "uint32_t \fBNumFrames\fP"
.br
.ti -1c
.RI "uint32_t \fBNumMaterials\fP"
.br
.ti -1c
.RI "uint64_t \fBVertexStreamHeadersOffset\fP"
.br
.ti -1c
.RI "uint64_t \fBIndexStreamHeadersOffset\fP"
.br
.ti -1c
.RI "uint64_t \fBMeshDataOffset\fP"
.br
.ti -1c
.RI "uint64_t \fBSubsetDataOffset\fP"
.br
.ti -1c
.RI "uint64_t \fBFrameDataOffset\fP"
.br
.ti -1c
.RI "uint64_t \fBMaterialDataOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
