.TH "DXUT::SDKANIMATION_DATA" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::SDKANIMATION_DATA
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DirectX::XMFLOAT3 \fBTranslation\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4 \fBOrientation\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT3 \fBScaling\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
