.TH "DXUT::SDKANIMATION_FILE_HEADER" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::SDKANIMATION_FILE_HEADER
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBVersion\fP"
.br
.ti -1c
.RI "uint8_t \fBIsBigEndian\fP"
.br
.ti -1c
.RI "uint32_t \fBFrameTransformType\fP"
.br
.ti -1c
.RI "uint32_t \fBNumFrames\fP"
.br
.ti -1c
.RI "uint32_t \fBNumAnimationKeys\fP"
.br
.ti -1c
.RI "uint32_t \fBAnimationFPS\fP"
.br
.ti -1c
.RI "uint64_t \fBAnimationDataSize\fP"
.br
.ti -1c
.RI "uint64_t \fBAnimationDataOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
