.TH "DXUT::SDKMESH_SUBSET" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::SDKMESH_SUBSET
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBName\fP [MAX_SUBSET_NAME]"
.br
.ti -1c
.RI "uint32_t \fBMaterialID\fP"
.br
.ti -1c
.RI "uint32_t \fBPrimitiveType\fP"
.br
.ti -1c
.RI "uint64_t \fBIndexStart\fP"
.br
.ti -1c
.RI "uint64_t \fBIndexCount\fP"
.br
.ti -1c
.RI "uint64_t \fBVertexStart\fP"
.br
.ti -1c
.RI "uint64_t \fBVertexCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
