.TH "DXUT::SDKMESH_MATERIAL_V2" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::SDKMESH_MATERIAL_V2
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBName\fP [MAX_MATERIAL_NAME]"
.br
.ti -1c
.RI "char \fBRMATexture\fP [MAX_TEXTURE_NAME]"
.br
.ti -1c
.RI "char \fBAlbedoTexture\fP [MAX_TEXTURE_NAME]"
.br
.ti -1c
.RI "char \fBNormalTexture\fP [MAX_TEXTURE_NAME]"
.br
.ti -1c
.RI "char \fBEmissiveTexture\fP [MAX_TEXTURE_NAME]"
.br
.ti -1c
.RI "float \fBAlpha\fP"
.br
.ti -1c
.RI "char \fBReserved\fP [60]"
.br
.ti -1c
.RI "uint64_t \fBForce64_1\fP"
.br
.ti -1c
.RI "uint64_t \fBForce64_2\fP"
.br
.ti -1c
.RI "uint64_t \fBForce64_3\fP"
.br
.ti -1c
.RI "uint64_t \fBForce64_4\fP"
.br
.ti -1c
.RI "uint64_t \fBForce64_5\fP"
.br
.ti -1c
.RI "uint64_t \fBForce64_6\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
