.TH "DXUT::SDKMESH_VERTEX_BUFFER_HEADER" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DXUT::SDKMESH_VERTEX_BUFFER_HEADER
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBNumVertices\fP"
.br
.ti -1c
.RI "uint64_t \fBSizeBytes\fP"
.br
.ti -1c
.RI "uint64_t \fBStrideBytes\fP"
.br
.ti -1c
.RI "\fBD3DVERTEXELEMENT9\fP \fBDecl\fP [MAX_VERTEX_ELEMENTS]"
.br
.ti -1c
.RI "uint64_t \fBDataOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
