.TH "Engine" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "GET float \fBget_delta_time\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWorld\fP \fBworld\fP"
.br
.ti -1c
.RI "\fBWindow\fP \fBwindow\fP"
.br
.ti -1c
.RI "\fBRenderer\fP \fBrenderer\fP"
.br
.ti -1c
.RI "bool \fBrunning\fP = true"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
