.TH "GenerateMipsCB" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenerateMipsCB
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINT \fBsrc_mip_level\fP"
.br
.ti -1c
.RI "UINT \fBnum_mip_levels\fP"
.br
.ti -1c
.RI "UINT \fBsrc_dimension\fP"
.br
.ti -1c
.RI "bool \fBis_srgb\fP"
.br
.ti -1c
.RI "\fBFVector2\fP \fBtexel_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
