.TH "GraphicsPipeline::RootSignature::ConstantBufferContainer< T >" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::ConstantBufferContainer< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantBufferContainer\fP (const T &obj)"
.br
.ti -1c
.RI "void \fBapply\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBConstantBufferContainer\fP &c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< T > \fBobj\fP = { }"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::ConstantBuffer\fP \fBcb\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
