.TH "GraphicsPipeline::RootSignature::ShaderResourceView" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::ShaderResourceView
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShaderResourceView\fP (const DirectX::ScratchImage &mip_chain, bool is_texture_cube=false)"
.br
.ti -1c
.RI "void \fBcompile\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list, const ComPtr< ID3D12DescriptorHeap > descriptor_heaps[NUMBER_OF_BUFFERS])"
.br
.ti -1c
.RI "void \fBupdate\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ComPtr< ID3D12Resource > \fBdefault_buffer\fP = nullptr"
.br
.ti -1c
.RI "D3D12_RESOURCE_DESC \fBheap_desc\fP = { }"
.br
.ti -1c
.RI "std::vector< D3D12_SUBRESOURCE_DATA > \fBsubresources\fP = { }"
.br
.ti -1c
.RI "D3D12_SHADER_RESOURCE_VIEW_DESC \fBsrv_desc\fP = { }"
.br
.ti -1c
.RI "UINT \fBindex\fP = 0u"
.br
.ti -1c
.RI "UINT \fBheap_index\fP = 0u"
.br
.ti -1c
.RI "bool \fBupdate_signal\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
