.TH "GraphicsPipelineMeshChangeInfo" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipelineMeshChangeInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::pair< \fBMesh\fP, size_t > > \fBadditions\fP"
.br
.ti -1c
.RI "std::vector< size_t > \fBsubtractions\fP"
.br
.ti -1c
.RI "std::vector< GraphicsPipelineMeshChangeInfoType > \fBorder\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
