.TH "GraphicsPipelineMeshChange::Command" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipelineMeshChange::Command \- Addition or removal information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipelineMeshChange\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBType\fP { \fBAdd\fP, \fBSub\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Type \fBtype\fP"
.br
.ti -1c
.RI "std::variant< std::pair< \fBMesh\fP, size_t >, size_t > \fBchange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Addition or removal information\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
