.TH "GraphicsAdapter" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsAdapter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGraphicsAdapter\fP (const ComPtr< IDXGIFactory2 > &factory)"
.br
.ti -1c
.RI "\fBGraphicsAdapter\fP (const ComPtr< IDXGIFactory2 > &factory, UINT adapter)"
.br
.ti -1c
.RI "\fBGraphicsAdapter\fP (const ComPtr< IDXGIFactory2 > &factory, const std::string &adapter)"
.br
.ti -1c
.RI "\fBGraphicsAdapter\fP (const ComPtr< IDXGIAdapter3 > &adapter)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBGraphicsAdapter\fP &adapter)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "GET DXGI_ADAPTER_DESC \fBget_desc\fP ()"
.br
.ti -1c
.RI "GET DXGI_QUERY_VIDEO_MEMORY_INFO \fBget_memory_info\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ComPtr< IDXGIAdapter3 > \fBadapter\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
