.TH "GraphicsPipeline::StreamOutput" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::StreamOutput
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamOutput\fP (const D3D12_STREAM_OUTPUT_DESC &desc)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBStreamOutput\fP &stream_output) const noexcept"
.br
.ti -1c
.RI "D3D12_STREAM_OUTPUT_DESC \fBget_desc\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
