.TH "GraphicsPipelineMeshChangeManager" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipelineMeshChangeManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_mesh\fP (const \fBMesh\fP &mesh, size_t index=(size_t) \-1)"
.br
.ti -1c
.RI "void \fBremove_mesh\fP (size_t index)"
.br
.ti -1c
.RI "void \fBremove_all_meshes\fP ()"
.br
.ti -1c
.RI "\fBGraphicsPipelineMeshChangeInfo\fP \fBget_changes\fP (bool clear_changes)"
.br
.ti -1c
.RI "void \fBclear_change_info\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
