.TH "GraphicsPipeline::ConstantBuffer< T >" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::ConstantBuffer< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantBuffer\fP (const T &obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< T > \fBobj\fP = { }"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::ConstantBuffer\fP \fBcb\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
