.TH "GraphicsPipeline::Shaders" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::Shaders
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::weak_ptr< \fBShader\fP > \fBvs\fP {}"
.br
.ti -1c
.RI "std::weak_ptr< \fBShader\fP > \fBhs\fP {}"
.br
.ti -1c
.RI "std::weak_ptr< \fBShader\fP > \fBds\fP {}"
.br
.ti -1c
.RI "std::weak_ptr< \fBShader\fP > \fBgs\fP {}"
.br
.ti -1c
.RI "std::weak_ptr< \fBShader\fP > \fBps\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
