.TH "GraphicsPipeline::Rasterizer" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::Rasterizer \- \fBRasterizer\fP stage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipeline\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRasterizer\fP (const D3D12_RASTERIZER_DESC &desc)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBRasterizer\fP &rasterizer) const noexcept"
.br
.ti -1c
.RI "void \fBset_desc\fP (const D3D12_RASTERIZER_DESC &desc) noexcept"
.br
.ti -1c
.RI "GET D3D12_RASTERIZER_DESC \fBget_desc\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRasterizer\fP stage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
