.TH "GraphicsPipeline::RootSignature" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature \- Root signature of the pipeline\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipeline\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBRootSignature\fP &root_signature) const noexcept"
.br
.ti -1c
.RI "void \fBcompile\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list, \fBGraphicsResourceDescriptorHeap\fP &descriptor_heaps, const \fBShaders\fP &shaders)"
.br
.ti -1c
.RI "void \fBcompile_resources\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list, \fBGraphicsResourceDescriptorHeap\fP &descriptor_heaps)"
.br
.ti -1c
.RI "void \fBbind_shader_resource_parameters\fP (const std::weak_ptr< \fBShader\fP > &s)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "void \fBcheck_for_update\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list, \fBGraphicsResourceDescriptorHeap\fP &descriptor_heaps)"
.br
.ti -1c
.RI "void \fBrun\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list, \fBGraphicsResourceDescriptorHeap\fP &descriptor_heaps)"
.br
.ti -1c
.RI "void \fBcreate_views\fP (const ComPtr< ID3D12Device > &device, \fBGraphicsResourceDescriptorHeap\fP &descriptor_heaps)"
.br
.ti -1c
.RI "GET const std::map< std::string, std::shared_ptr< \fBConstantBuffer\fP > > & \fBget_constant_buffers\fP () const noexcept"
.br
.ti -1c
.RI "GET const std::map< std::string, std::shared_ptr< \fBRootConstants\fP > > & \fBget_root_constants\fP () const noexcept"
.br
.ti -1c
.RI "GET const std::map< std::string, std::shared_ptr< \fBShaderResourceView\fP > > & \fBget_shader_resource_views\fP () const noexcept"
.br
.ti -1c
.RI "GET std::weak_ptr< \fBDescriptorRootObject\fP > \fBget_resource\fP (const std::string &name) const"
.br
.ti -1c
.RI "GET std::weak_ptr< \fBConstantBuffer\fP > \fBget_constant_buffer\fP (const std::string &name) const"
.br
.ti -1c
.RI "GET std::weak_ptr< \fBRootConstants\fP > \fBget_root_constants\fP (const std::string &name) const"
.br
.ti -1c
.RI "GET std::weak_ptr< \fBShaderResourceView\fP > \fBget_shader_resource_view\fP (const std::string &name) const"
.br
.ti -1c
.RI "GET std::vector< D3D12_ROOT_PARAMETER1 > \fBget_root_params\fP () const noexcept"
.br
.ti -1c
.RI "GET size_t \fBget_number_of_params\fP () const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
Root signature of the pipeline\&. 

Uploads data and structures to shaders\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
