.TH "GraphicsScene" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsScene
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<ACCEPT_BASE_AND_HEIRS_ONLY(typename T, \fBGraphicsComponent\fP) > void \fBadd_component\fP (const T *component)"
.br
.ti -1c
.RI "template<ACCEPT_BASE_AND_HEIRS_ONLY(typename T, \fBGraphicsComponent\fP) > void \fBremove_component\fP (const T *component)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRenderer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
