.TH "GraphicsPipeline::RootSignature::RootConstants" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::RootConstants \- Root constants\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipeline\&.h>\fP
.PP
Inherits \fBGraphicsPipeline::RootSignature::RootArgument\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBRootConstants\fP (T &obj, D3D12_SHADER_VISIBILITY shader, UINT index, UINT parameter_index, UINT number_of_values=\-1)"
.br
.ti -1c
.RI "template<typename T > void \fBset_obj\fP (T *obj)"
.br
.ti -1c
.RI "void \fBcompile\fP (D3D12_SHADER_VISIBILITY shader, UINT parameter_index, UINT index, UINT number_of_values=\-1)"
.br
.ti -1c
.RI "template<typename T > void \fBcompile\fP (T &obj, D3D12_SHADER_VISIBILITY shader, UINT index, UINT number_of_values=\-1)"
.br
.ti -1c
.RI "const D3D12_ROOT_CONSTANTS & \fBget_constants\fP () const noexcept"
.br
.in -1c

Public Member Functions inherited from \fBGraphicsPipeline::RootSignature::RootArgument\fP
.in +1c
.ti -1c
.RI "\fBRootArgument\fP (UINT parameter_index)"
.br
.ti -1c
.RI "UINT \fBget_parameter_index\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBGraphicsPipeline::RootSignature::RootArgument\fP
.in +1c
.ti -1c
.RI "friend \fBRootSignature\fP"
.br
.ti -1c
.RI "std::vector< D3D12_ROOT_PARAMETER > \fBroot_parameters\fP = { }"
.br
.ti -1c
.RI "UINT \fBparameter_index\fP {(UINT)\-1}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Root constants\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
