.TH "GraphicsPipeline::RootSignature::ConstantBuffer" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::ConstantBuffer \- Constant buffer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipeline\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBConstantBuffer\fP (T &cb, std::string name='')"
.br
.ti -1c
.RI "void \fBcompile\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list, \fBGraphicsDescriptorHeaps\fP &descriptor_heaps)"
.br
.ti -1c
.RI "void \fBupdate\fP (const ComPtr< ID3D12Device > &device, const ComPtr< ID3D12GraphicsCommandList > &command_list)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBConstantBuffer\fP &cb) const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBobj\fP = nullptr"
.br
.ti -1c
.RI "size_t \fBobj_size\fP = 0u"
.br
.ti -1c
.RI "UINT \fBheap_index\fP {(UINT)\-1}"
.br
.ti -1c
.RI "std::string \fBname\fP = ''"
.br
.ti -1c
.RI "bool \fBupdate_signal\fP = true"
.br
.ti -1c
.RI "ComPtr< ID3D12Resource > \fBdefault_heap\fP {nullptr}"
.br
.ti -1c
.RI "std::shared_ptr< \fBDescriptorTable\fP > \fBdescriptor_table\fP {nullptr}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constant buffer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
