.TH "GraphicsPipeline::RootSignature::DescriptorTable" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::DescriptorTable \- Descriptor table to describe data to be uploaded\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipeline\&.h>\fP
.PP
Inherits \fBGraphicsPipeline::RootSignature::RootArgument\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDescriptorTable\fP (D3D12_DESCRIPTOR_RANGE_TYPE type, D3D12_SHADER_VISIBILITY shader, UINT index, UINT parameter_index)"
.br
.ti -1c
.RI "void \fBcompile\fP (D3D12_DESCRIPTOR_RANGE_TYPE type, D3D12_SHADER_VISIBILITY shader, UINT index)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBDescriptorTable\fP &descriptor_table) const noexcept"
.br
.ti -1c
.RI "const D3D12_ROOT_DESCRIPTOR_TABLE & \fBget_table\fP () const noexcept"
.br
.ti -1c
.RI "const std::vector< CD3DX12_DESCRIPTOR_RANGE > & \fBget_ranges\fP () const noexcept"
.br
.in -1c

Public Member Functions inherited from \fBGraphicsPipeline::RootSignature::RootArgument\fP
.in +1c
.ti -1c
.RI "\fBRootArgument\fP (UINT parameter_index)"
.br
.ti -1c
.RI "UINT \fBget_parameter_index\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBGraphicsPipeline::RootSignature::RootArgument\fP
.in +1c
.ti -1c
.RI "friend \fBRootSignature\fP"
.br
.ti -1c
.RI "std::vector< D3D12_ROOT_PARAMETER > \fBroot_parameters\fP = { }"
.br
.ti -1c
.RI "UINT \fBparameter_index\fP {(UINT)\-1}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Descriptor table to describe data to be uploaded\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
