.TH "GraphicsPipeline::RootSignature::ConstantBufferContainer< T >" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::ConstantBufferContainer< T > \- Stores a structure and the constant buffer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipeline\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstantBufferContainer\fP (const T &obj)"
.br
.ti -1c
.RI "void \fBapply\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBConstantBufferContainer\fP &c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< T > \fBobj\fP = { }"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::ConstantBuffer\fP \fBcb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class GraphicsPipeline::RootSignature::ConstantBufferContainer< T >"Stores a structure and the constant buffer\&. 

The structure is the data to be written to the constant buffer\&. Not required, but useful\&. 
.PP
\fBSee also\fP
.RS 4
\fBGraphicsPipeline::RootSignature::ConstantBuffer\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
