.TH "GraphicsPipeline::RootSignature::RootConstants" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::RootConstants
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGraphicsPipeline::RootSignature::RootArgument\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRootConstants\fP (UINT parameter_index)"
.br
.ti -1c
.RI "template<typename T > \fBRootConstants\fP (T &obj, D3D12_SHADER_VISIBILITY shader, UINT index, UINT parameter_index, UINT number_of_values=\-1)"
.br
.ti -1c
.RI "template<typename T > void \fBset_obj\fP (T *obj)"
.br
.ti -1c
.RI "void \fBcompile\fP (D3D12_SHADER_VISIBILITY shader, UINT parameter_index, UINT index, UINT number_of_values=\-1)"
.br
.ti -1c
.RI "template<typename T > void \fBcompile\fP (T &obj, D3D12_SHADER_VISIBILITY shader, UINT index, UINT number_of_values=\-1)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBGraphicsPipeline::RootSignature::RootArgument\fP
.in +1c
.ti -1c
.RI "friend \fBRootSignature\fP"
.br
.ti -1c
.RI "std::vector< D3D12_ROOT_PARAMETER > \fBroot_parameters\fP = { }"
.br
.ti -1c
.RI "UINT \fBparameter_index\fP = 0u"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
