.TH "GraphicsPipeline::RootSignature::RootArgument" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::RootArgument
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGraphicsPipeline::RootSignature::DescriptorTable\fP, and \fBGraphicsPipeline::RootSignature::RootConstants\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "friend \fBRootSignature\fP"
.br
.ti -1c
.RI "std::vector< D3D12_ROOT_PARAMETER > \fBroot_parameters\fP = { }"
.br
.ti -1c
.RI "UINT \fBparameter_index\fP = 0u"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
