.TH "GraphicsPipeline::RootSignature::RootConstantsContainer< T >" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipeline::RootSignature::RootConstantsContainer< T > \- Stores a structure and the root constants\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipeline\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRootConstantsContainer\fP (const T &obj)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< T > \fBobj\fP = { }"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::RootConstants\fP \fBrc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class GraphicsPipeline::RootSignature::RootConstantsContainer< T >"Stores a structure and the root constants\&. 

The structure is the data to be written to the root constants\&. Not required, but useful\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
