.TH "GraphicsAdapterOutput" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsAdapterOutput
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGraphicsAdapterOutput\fP (const ComPtr< ID3D12Device > &device, const ComPtr< IDXGIAdapter > &adapter)"
.br
.ti -1c
.RI "\fBGraphicsAdapterOutput\fP (const ComPtr< ID3D12Device > &device, const ComPtr< IDXGIAdapter > &adapter, UINT adapter_output)"
.br
.ti -1c
.RI "\fBGraphicsAdapterOutput\fP (const ComPtr< ID3D12Device > &device, const ComPtr< IDXGIAdapter > &adapter, const std::string &adapter_output)"
.br
.ti -1c
.RI "\fBGraphicsAdapterOutput\fP (const ComPtr< ID3D12Device > &device, const ComPtr< IDXGIOutput > &adapter_output)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBGraphicsAdapterOutput\fP &adapter_output)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "GET DXGI_OUTPUT_DESC \fBget_desc\fP ()"
.br
.ti -1c
.RI "GET DXGI_MODE_DESC \fBget_mode_desc\fP ()"
.br
.ti -1c
.RI "GET MONITORINFOEXA \fBget_monitor_info\fP ()"
.br
.ti -1c
.RI "GET DISPLAY_DEVICEA \fBget_display_device\fP ()"
.br
.ti -1c
.RI "GET DXGI_GAMMA_CONTROL \fBget_gamma_control\fP ()"
.br
.ti -1c
.RI "GET DXGI_GAMMA_CONTROL_CAPABILITIES \fBget_gamma_control_capabilities\fP ()"
.br
.ti -1c
.RI "void \fBset_gamma_control\fP (const DXGI_GAMMA_CONTROL &gamma_control)"
.br
.ti -1c
.RI "DXGI_MODE_DESC \fBfind_closest_display_mode_to_current\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ComPtr< IDXGIOutput > \fBadapter_output\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
