.TH "GraphicsTracker" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsTracker
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGraphicsComponent\fP, \fBMaterial\fP, and \fBTexture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool changed) noexcept"
.br
.ti -1c
.RI "bool \fBneeds_compile\fP () const noexcept"
.br
.ti -1c
.RI "void \fBneeds_compile\fP (bool compile) noexcept"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBchanged\fP {false}"
.br
.ti -1c
.RI "bool \fBcompile\fP {false}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
