.TH "GraphicsPipelineMeshChange::Manager" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsPipelineMeshChange::Manager \- Stores additions and removals of meshes in the pipeline\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsPipelineMeshChange\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_mesh\fP (const \fBMesh\fP &mesh, size_t index=(size_t) \-1)"
.br
.ti -1c
.RI "void \fBremove_mesh\fP (size_t index)"
.br
.ti -1c
.RI "void \fBremove_all_meshes\fP ()"
.br
.ti -1c
.RI "std::vector< \fBCommand\fP > \fBget_changes\fP (bool clear_changes)"
.br
.ti -1c
.RI "void \fBclear_change_info\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores additions and removals of meshes in the pipeline\&. 

Communicates these changes from the \fBStaticMeshComponent\fP to the \fBGraphicsPipeline\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fBStaticMeshComponent\fP 
.PP
\fBGraphicsPipeline\fP 
.PP
\fBMesh\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
