.TH "ImDrawCmdHeader" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawCmdHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec4\fP \fBClipRect\fP"
.br
.ti -1c
.RI "ImTextureID \fBTextureId\fP"
.br
.ti -1c
.RI "unsigned int \fBVtxOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
