.TH "ImDrawChannel" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawChannel
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImDrawCmd\fP > \fB_CmdBuffer\fP"
.br
.ti -1c
.RI "\fBImVector\fP< ImDrawIdx > \fB_IdxBuffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
