.TH "ImGuiTabItem" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTabItem
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiTabItemFlags \fBFlags\fP"
.br
.ti -1c
.RI "int \fBLastFrameVisible\fP"
.br
.ti -1c
.RI "int \fBLastFrameSelected\fP"
.br
.ti -1c
.RI "float \fBOffset\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "float \fBContentWidth\fP"
.br
.ti -1c
.RI "float \fBRequestedWidth\fP"
.br
.ti -1c
.RI "ImS32 \fBNameOffset\fP"
.br
.ti -1c
.RI "ImS16 \fBBeginOrder\fP"
.br
.ti -1c
.RI "ImS16 \fBIndexDuringLayout\fP"
.br
.ti -1c
.RI "bool \fBWantClose\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
