.TH "ImGuiKeyOwnerData" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiKeyOwnerData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBOwnerCurr\fP"
.br
.ti -1c
.RI "ImGuiID \fBOwnerNext\fP"
.br
.ti -1c
.RI "bool \fBLockThisFrame\fP"
.br
.ti -1c
.RI "bool \fBLockUntilRelease\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
