.TH "ImGuiNextItemData" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNextItemData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearFlags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiNextItemDataFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImGuiItemFlags \fBItemFlags\fP"
.br
.ti -1c
.RI "ImGuiSelectionUserData \fBSelectionUserData\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "ImGuiKeyChord \fBShortcut\fP"
.br
.ti -1c
.RI "bool \fBOpenVal\fP"
.br
.ti -1c
.RI "ImGuiCond \fBOpenCond\fP: 8"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
