.TH "ImGuiWindowSettings" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetName\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBSize\fP"
.br
.ti -1c
.RI "bool \fBCollapsed\fP"
.br
.ti -1c
.RI "bool \fBIsChild\fP"
.br
.ti -1c
.RI "bool \fBWantApply\fP"
.br
.ti -1c
.RI "bool \fBWantDelete\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
