.TH "ImGuiTableInstanceData" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableInstanceData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBTableInstanceID\fP"
.br
.ti -1c
.RI "float \fBLastOuterHeight\fP"
.br
.ti -1c
.RI "float \fBLastTopHeadersRowHeight\fP"
.br
.ti -1c
.RI "float \fBLastFrozenHeight\fP"
.br
.ti -1c
.RI "int \fBHoveredRowLast\fP"
.br
.ti -1c
.RI "int \fBHoveredRowNext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
