.TH "ImGui_ImplDX12_Data" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplDX12_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ID3D12Device * \fBpd3dDevice\fP"
.br
.ti -1c
.RI "ID3D12RootSignature * \fBpRootSignature\fP"
.br
.ti -1c
.RI "ID3D12PipelineState * \fBpPipelineState\fP"
.br
.ti -1c
.RI "DXGI_FORMAT \fBRTVFormat\fP"
.br
.ti -1c
.RI "DXGI_SAMPLE_DESC \fBsampleDesc\fP"
.br
.ti -1c
.RI "ID3D12Resource * \fBpFontTextureResource\fP"
.br
.ti -1c
.RI "D3D12_CPU_DESCRIPTOR_HANDLE \fBhFontSrvCpuDescHandle\fP"
.br
.ti -1c
.RI "D3D12_GPU_DESCRIPTOR_HANDLE \fBhFontSrvGpuDescHandle\fP"
.br
.ti -1c
.RI "ID3D12DescriptorHeap * \fBpd3dSrvDescHeap\fP"
.br
.ti -1c
.RI "UINT \fBnumFramesInFlight\fP"
.br
.ti -1c
.RI "\fBImGui_ImplDX12_RenderBuffers\fP * \fBpFrameResources\fP"
.br
.ti -1c
.RI "UINT \fBframeIndex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
