.TH "ImGuiInputEventMousePos" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiInputEventMousePos
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBPosX\fP"
.br
.ti -1c
.RI "float \fBPosY\fP"
.br
.ti -1c
.RI "ImGuiMouseSource \fBMouseSource\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
