.TH "ImGuiTypingSelectState" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTypingSelectState
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiTypingSelectRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "char \fBSearchBuffer\fP [64]"
.br
.ti -1c
.RI "ImGuiID \fBFocusScope\fP"
.br
.ti -1c
.RI "int \fBLastRequestFrame\fP = 0"
.br
.ti -1c
.RI "float \fBLastRequestTime\fP = 0\&.0f"
.br
.ti -1c
.RI "bool \fBSingleCharModeLock\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
