.TH "ImGui_ImplDX12_RenderBuffers" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplDX12_RenderBuffers
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ID3D12Resource * \fBIndexBuffer\fP"
.br
.ti -1c
.RI "ID3D12Resource * \fBVertexBuffer\fP"
.br
.ti -1c
.RI "int \fBIndexBufferSize\fP"
.br
.ti -1c
.RI "int \fBVertexBufferSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
