.TH "ImGuiMetricsConfig" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMetricsConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBShowDebugLog\fP = false"
.br
.ti -1c
.RI "bool \fBShowIDStackTool\fP = false"
.br
.ti -1c
.RI "bool \fBShowWindowsRects\fP = false"
.br
.ti -1c
.RI "bool \fBShowWindowsBeginOrder\fP = false"
.br
.ti -1c
.RI "bool \fBShowTablesRects\fP = false"
.br
.ti -1c
.RI "bool \fBShowDrawCmdMesh\fP = true"
.br
.ti -1c
.RI "bool \fBShowDrawCmdBoundingBoxes\fP = true"
.br
.ti -1c
.RI "bool \fBShowTextEncodingViewer\fP = false"
.br
.ti -1c
.RI "bool \fBShowAtlasTintedWithTextColor\fP = false"
.br
.ti -1c
.RI "int \fBShowWindowsRectsType\fP = \-1"
.br
.ti -1c
.RI "int \fBShowTablesRectsType\fP = \-1"
.br
.ti -1c
.RI "int \fBHighlightMonitorIdx\fP = \-1"
.br
.ti -1c
.RI "ImGuiID \fBHighlightViewportID\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
