.TH "ImGuiWindowStackData" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowStackData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "\fBImGuiLastItemData\fP \fBParentLastItemDataBackup\fP"
.br
.ti -1c
.RI "\fBImGuiStackSizes\fP \fBStackSizesOnBegin\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
