.TH "ImGuiComboPreviewData" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiComboPreviewData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImRect\fP \fBPreviewRect\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPosPrevLine\fP"
.br
.ti -1c
.RI "float \fBBackupPrevLineTextBaseOffset\fP"
.br
.ti -1c
.RI "ImGuiLayoutType \fBBackupLayout\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
