.TH "ImGuiDebugAllocInfo" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDebugAllocInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTotalAllocCount\fP"
.br
.ti -1c
.RI "int \fBTotalFreeCount\fP"
.br
.ti -1c
.RI "ImS16 \fBLastEntriesIdx\fP"
.br
.ti -1c
.RI "\fBImGuiDebugAllocEntry\fP \fBLastEntriesBuf\fP [6]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
