.TH "ImGuiTypingSelectRequest" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTypingSelectRequest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiTypingSelectFlags \fBFlags\fP"
.br
.ti -1c
.RI "int \fBSearchBufferLen\fP"
.br
.ti -1c
.RI "const char * \fBSearchBuffer\fP"
.br
.ti -1c
.RI "bool \fBSelectRequest\fP"
.br
.ti -1c
.RI "bool \fBSingleCharMode\fP"
.br
.ti -1c
.RI "ImS8 \fBSingleCharSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
