.TH "ImGuiInputEventMouseWheel" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiInputEventMouseWheel
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBWheelX\fP"
.br
.ti -1c
.RI "float \fBWheelY\fP"
.br
.ti -1c
.RI "ImGuiMouseSource \fBMouseSource\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
