.TH "ImGuiIDStackTool" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiIDStackTool
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBLastActiveFrame\fP"
.br
.ti -1c
.RI "int \fBStackLevel\fP"
.br
.ti -1c
.RI "ImGuiID \fBQueryId\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiStackLevelInfo\fP > \fBResults\fP"
.br
.ti -1c
.RI "bool \fBCopyToClipboardOnCtrlC\fP"
.br
.ti -1c
.RI "float \fBCopyToClipboardLastTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
