.TH "ImGui_ImplWin32_Data" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplWin32_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HWND \fBhWnd\fP"
.br
.ti -1c
.RI "HWND \fBMouseHwnd\fP"
.br
.ti -1c
.RI "int \fBMouseTrackedArea\fP"
.br
.ti -1c
.RI "int \fBMouseButtonsDown\fP"
.br
.ti -1c
.RI "INT64 \fBTime\fP"
.br
.ti -1c
.RI "INT64 \fBTicksPerSecond\fP"
.br
.ti -1c
.RI "ImGuiMouseCursor \fBLastMouseCursor\fP"
.br
.ti -1c
.RI "UINT32 \fBKeyboardCodePage\fP"
.br
.ti -1c
.RI "bool \fBHasGamepad\fP"
.br
.ti -1c
.RI "bool \fBWantUpdateHasGamepad\fP"
.br
.ti -1c
.RI "HMODULE \fBXInputDLL\fP"
.br
.ti -1c
.RI "PFN_XInputGetCapabilities \fBXInputGetCapabilities\fP"
.br
.ti -1c
.RI "PFN_XInputGetState \fBXInputGetState\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
