.TH "ImPlotAlignmentData" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotAlignmentData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBegin\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP (float &pad_a, float &pad_b, float &delta_a, float &delta_b)"
.br
.ti -1c
.RI "void \fBEnd\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBVertical\fP"
.br
.ti -1c
.RI "float \fBPadA\fP"
.br
.ti -1c
.RI "float \fBPadB\fP"
.br
.ti -1c
.RI "float \fBPadAMax\fP"
.br
.ti -1c
.RI "float \fBPadBMax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
