.TH "ImPlotStyle" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotStyle
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBLineWeight\fP"
.br
.ti -1c
.RI "int \fBMarker\fP"
.br
.ti -1c
.RI "float \fBMarkerSize\fP"
.br
.ti -1c
.RI "float \fBMarkerWeight\fP"
.br
.ti -1c
.RI "float \fBFillAlpha\fP"
.br
.ti -1c
.RI "float \fBErrorBarSize\fP"
.br
.ti -1c
.RI "float \fBErrorBarWeight\fP"
.br
.ti -1c
.RI "float \fBDigitalBitHeight\fP"
.br
.ti -1c
.RI "float \fBDigitalBitGap\fP"
.br
.ti -1c
.RI "float \fBPlotBorderSize\fP"
.br
.ti -1c
.RI "float \fBMinorAlpha\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMajorTickLen\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMinorTickLen\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMajorTickSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMinorTickSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMajorGridSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMinorGridSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPlotPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLabelPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLegendPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLegendInnerPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLegendSpacing\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBMousePosPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBAnnotationPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBFitPadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPlotDefaultSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPlotMinSize\fP"
.br
.ti -1c
.RI "\fBImVec4\fP \fBColors\fP [ImPlotCol_COUNT]"
.br
.ti -1c
.RI "ImPlotColormap \fBColormap\fP"
.br
.ti -1c
.RI "bool \fBUseLocalTime\fP"
.br
.ti -1c
.RI "bool \fBUseISO8601\fP"
.br
.ti -1c
.RI "bool \fBUse24HourClock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
