.TH "ImPlotNextItemData" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotNextItemData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec4\fP \fBColors\fP [5]"
.br
.ti -1c
.RI "float \fBLineWeight\fP"
.br
.ti -1c
.RI "ImPlotMarker \fBMarker\fP"
.br
.ti -1c
.RI "float \fBMarkerSize\fP"
.br
.ti -1c
.RI "float \fBMarkerWeight\fP"
.br
.ti -1c
.RI "float \fBFillAlpha\fP"
.br
.ti -1c
.RI "float \fBErrorBarSize\fP"
.br
.ti -1c
.RI "float \fBErrorBarWeight\fP"
.br
.ti -1c
.RI "float \fBDigitalBitHeight\fP"
.br
.ti -1c
.RI "float \fBDigitalBitGap\fP"
.br
.ti -1c
.RI "bool \fBRenderLine\fP"
.br
.ti -1c
.RI "bool \fBRenderFill\fP"
.br
.ti -1c
.RI "bool \fBRenderMarkerLine\fP"
.br
.ti -1c
.RI "bool \fBRenderMarkerFill\fP"
.br
.ti -1c
.RI "bool \fBHasHidden\fP"
.br
.ti -1c
.RI "bool \fBHidden\fP"
.br
.ti -1c
.RI "ImPlotCond \fBHiddenCond\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
