.TH "ImPlotTag" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotTag
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImAxis \fBAxis\fP"
.br
.ti -1c
.RI "double \fBValue\fP"
.br
.ti -1c
.RI "ImU32 \fBColorBg\fP"
.br
.ti -1c
.RI "ImU32 \fBColorFg\fP"
.br
.ti -1c
.RI "int \fBTextOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
