.TH "ImPlot::Formatter_Time_Data" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::Formatter_Time_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImPlotTime\fP \fBTime\fP"
.br
.ti -1c
.RI "\fBImPlotDateTimeSpec\fP \fBSpec\fP"
.br
.ti -1c
.RI "ImPlotFormatter \fBUserFormatter\fP"
.br
.ti -1c
.RI "void * \fBUserFormatterData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
