.TH "ImPlot::FitterBarH< _Getter1, _Getter2 >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::FitterBarH< _Getter1, _Getter2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFitterBarH\fP (const _Getter1 &getter1, const _Getter2 &getter2, double height)"
.br
.ti -1c
.RI "void \fBFit\fP (\fBImPlotAxis\fP &x_axis, \fBImPlotAxis\fP &y_axis) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _Getter1 & \fBGetter1\fP"
.br
.ti -1c
.RI "const _Getter2 & \fBGetter2\fP"
.br
.ti -1c
.RI "const double \fBHalfHeight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
