.TH "ImPlotDateTimeSpec" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotDateTimeSpec
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImPlotDateTimeSpec\fP (ImPlotDateFmt date_fmt, ImPlotTimeFmt time_fmt, bool use_24_hr_clk=false, bool use_iso_8601=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImPlotDateFmt \fBDate\fP"
.br
.ti -1c
.RI "ImPlotTimeFmt \fBTime\fP"
.br
.ti -1c
.RI "bool \fBUseISO8601\fP"
.br
.ti -1c
.RI "bool \fBUse24HourClock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
