.TH "ImPlot::HugeTimeData" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::HugeTimeData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHugeTimeData\fP (double min)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBGetY\fP (double t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double * \fBTs\fP"
.br
.ti -1c
.RI "double * \fBYs\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBSize\fP = 60*60*24*366"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
