.TH "ImPlot::FitterX< _Getter1 >" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::FitterX< _Getter1 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFitterX\fP (const _Getter1 &getter)"
.br
.ti -1c
.RI "void \fBFit\fP (\fBImPlotAxis\fP &x_axis, \fBImPlotAxis\fP &) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _Getter1 & \fBGetter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
