.TH "ImPlotRange" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotRange
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBImPlotRange\fP (double _min, double _max)"
.br
.ti -1c
.RI "bool \fBContains\fP (double value) const"
.br
.ti -1c
.RI "double \fBSize\fP () const"
.br
.ti -1c
.RI "double \fBClamp\fP (double value) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBMin\fP"
.br
.ti -1c
.RI "double \fBMax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
