.TH "ImPlot::NormalDistribution< N >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::NormalDistribution< N >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNormalDistribution\fP (double mean, double sd)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBData\fP [N]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
