.TH "ImPlot::FitterY< _Getter1 >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::FitterY< _Getter1 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFitterY\fP (const _Getter1 &getter)"
.br
.ti -1c
.RI "void \fBFit\fP (\fBImPlotAxis\fP &, \fBImPlotAxis\fP &y_axis) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _Getter1 & \fBGetter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
