.TH "ImPlot::IndexerIdx< T >" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::IndexerIdx< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexerIdx\fP (const T *data, int count, int offset=0, int stride=sizeof(T))"
.br
.ti -1c
.RI "template<typename I > IMPLOT_INLINE double \fBoperator()\fP (I idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const T * \fBData\fP"
.br
.ti -1c
.RI "int \fBCount\fP"
.br
.ti -1c
.RI "int \fBOffset\fP"
.br
.ti -1c
.RI "int \fBStride\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
