.TH "ImPlotTime" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotTime
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImPlotTime\fP (time_t s, int us=0)"
.br
.ti -1c
.RI "void \fBRollOver\fP ()"
.br
.ti -1c
.RI "double \fBToDouble\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBImPlotTime\fP \fBFromDouble\fP (double t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time_t \fBS\fP"
.br
.ti -1c
.RI "int \fBUs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
