.TH "ImPlot::GetterHeatmapColMaj< T >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::GetterHeatmapColMaj< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetterHeatmapColMaj\fP (const T *values, int rows, int cols, double scale_min, double scale_max, double width, double height, double xref, double yref, double ydir)"
.br
.ti -1c
.RI "template<typename I > IMPLOT_INLINE \fBRectC\fP \fBoperator()\fP (I idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const T *const \fBValues\fP"
.br
.ti -1c
.RI "const int \fBCount\fP"
.br
.ti -1c
.RI "const int \fBRows\fP"
.br
.ti -1c
.RI "const int \fBCols\fP"
.br
.ti -1c
.RI "const double \fBScaleMin\fP"
.br
.ti -1c
.RI "const double \fBScaleMax\fP"
.br
.ti -1c
.RI "const double \fBWidth\fP"
.br
.ti -1c
.RI "const double \fBHeight\fP"
.br
.ti -1c
.RI "const double \fBXRef\fP"
.br
.ti -1c
.RI "const double \fBYRef\fP"
.br
.ti -1c
.RI "const double \fBYDir\fP"
.br
.ti -1c
.RI "const \fBImPlotPoint\fP \fBHalfSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
