.TH "ImPlotContext" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotContext
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImPool\fP< \fBImPlotPlot\fP > \fBPlots\fP"
.br
.ti -1c
.RI "\fBImPool\fP< \fBImPlotSubplot\fP > \fBSubplots\fP"
.br
.ti -1c
.RI "\fBImPlotPlot\fP * \fBCurrentPlot\fP"
.br
.ti -1c
.RI "\fBImPlotSubplot\fP * \fBCurrentSubplot\fP"
.br
.ti -1c
.RI "\fBImPlotItemGroup\fP * \fBCurrentItems\fP"
.br
.ti -1c
.RI "\fBImPlotItem\fP * \fBCurrentItem\fP"
.br
.ti -1c
.RI "\fBImPlotItem\fP * \fBPreviousItem\fP"
.br
.ti -1c
.RI "\fBImPlotTicker\fP \fBCTicker\fP"
.br
.ti -1c
.RI "\fBImPlotAnnotationCollection\fP \fBAnnotations\fP"
.br
.ti -1c
.RI "\fBImPlotTagCollection\fP \fBTags\fP"
.br
.ti -1c
.RI "\fBImPlotStyle\fP \fBStyle\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiColorMod\fP > \fBColorModifiers\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImGuiStyleMod\fP > \fBStyleModifiers\fP"
.br
.ti -1c
.RI "\fBImPlotColormapData\fP \fBColormapData\fP"
.br
.ti -1c
.RI "\fBImVector\fP< ImPlotColormap > \fBColormapModifiers\fP"
.br
.ti -1c
.RI "tm \fBTm\fP"
.br
.ti -1c
.RI "\fBImVector\fP< double > \fBTempDouble1\fP"
.br
.ti -1c
.RI "\fBImVector\fP< double > \fBTempDouble2\fP"
.br
.ti -1c
.RI "\fBImVector\fP< int > \fBTempInt1\fP"
.br
.ti -1c
.RI "int \fBDigitalPlotItemCnt\fP"
.br
.ti -1c
.RI "int \fBDigitalPlotOffset\fP"
.br
.ti -1c
.RI "\fBImPlotNextPlotData\fP \fBNextPlotData\fP"
.br
.ti -1c
.RI "\fBImPlotNextItemData\fP \fBNextItemData\fP"
.br
.ti -1c
.RI "\fBImPlotInputMap\fP \fBInputMap\fP"
.br
.ti -1c
.RI "bool \fBOpenContextThisFrame\fP"
.br
.ti -1c
.RI "\fBImGuiTextBuffer\fP \fBMousePosStringBuilder\fP"
.br
.ti -1c
.RI "\fBImPlotItemGroup\fP * \fBSortItems\fP"
.br
.ti -1c
.RI "\fBImPool\fP< \fBImPlotAlignmentData\fP > \fBAlignmentData\fP"
.br
.ti -1c
.RI "\fBImPlotAlignmentData\fP * \fBCurrentAlignmentH\fP"
.br
.ti -1c
.RI "\fBImPlotAlignmentData\fP * \fBCurrentAlignmentV\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
