.TH "ImPlot::FitterRect" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::FitterRect
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFitterRect\fP (const \fBImPlotPoint\fP &pmin, const \fBImPlotPoint\fP &pmax)"
.br
.ti -1c
.RI "\fBFitterRect\fP (const \fBImPlotRect\fP &rect)"
.br
.ti -1c
.RI "void \fBFit\fP (\fBImPlotAxis\fP &x_axis, \fBImPlotAxis\fP &y_axis) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBImPlotPoint\fP \fBPmin\fP"
.br
.ti -1c
.RI "const \fBImPlotPoint\fP \fBPmax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
