.TH "ImPlotInputMap" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotInputMap
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiMouseButton \fBPan\fP"
.br
.ti -1c
.RI "int \fBPanMod\fP"
.br
.ti -1c
.RI "ImGuiMouseButton \fBFit\fP"
.br
.ti -1c
.RI "ImGuiMouseButton \fBSelect\fP"
.br
.ti -1c
.RI "ImGuiMouseButton \fBSelectCancel\fP"
.br
.ti -1c
.RI "int \fBSelectMod\fP"
.br
.ti -1c
.RI "int \fBSelectHorzMod\fP"
.br
.ti -1c
.RI "int \fBSelectVertMod\fP"
.br
.ti -1c
.RI "ImGuiMouseButton \fBMenu\fP"
.br
.ti -1c
.RI "int \fBOverrideMod\fP"
.br
.ti -1c
.RI "int \fBZoomMod\fP"
.br
.ti -1c
.RI "float \fBZoomRate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
