.TH "ImPlotTick" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotTick
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImPlotTick\fP (double value, bool major, int level, bool show_label)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBPlotPos\fP"
.br
.ti -1c
.RI "float \fBPixelPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLabelSize\fP"
.br
.ti -1c
.RI "int \fBTextOffset\fP"
.br
.ti -1c
.RI "bool \fBMajor\fP"
.br
.ti -1c
.RI "bool \fBShowLabel\fP"
.br
.ti -1c
.RI "int \fBLevel\fP"
.br
.ti -1c
.RI "int \fBIdx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
