.TH "ImPlotLegend" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotLegend
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImPlotLegendFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImPlotLegendFlags \fBPreviousFlags\fP"
.br
.ti -1c
.RI "ImPlotLocation \fBLocation\fP"
.br
.ti -1c
.RI "ImPlotLocation \fBPreviousLocation\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBScroll\fP"
.br
.ti -1c
.RI "\fBImVector\fP< int > \fBIndices\fP"
.br
.ti -1c
.RI "\fBImGuiTextBuffer\fP \fBLabels\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBRectClamped\fP"
.br
.ti -1c
.RI "bool \fBHovered\fP"
.br
.ti -1c
.RI "bool \fBHeld\fP"
.br
.ti -1c
.RI "bool \fBCanGoInside\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
