.TH "ImPlot::GetterXY< _IndexerX, _IndexerY >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::GetterXY< _IndexerX, _IndexerY >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetterXY\fP (_IndexerX x, _IndexerY y, int count)"
.br
.ti -1c
.RI "template<typename I > IMPLOT_INLINE \fBImPlotPoint\fP \fBoperator()\fP (I idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _IndexerX \fBIndxerX\fP"
.br
.ti -1c
.RI "const _IndexerY \fBIndxerY\fP"
.br
.ti -1c
.RI "const int \fBCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
