.TH "ImPlotSubplot" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotSubplot
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImPlotSubplotFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImPlotSubplotFlags \fBPreviousFlags\fP"
.br
.ti -1c
.RI "\fBImPlotItemGroup\fP \fBItems\fP"
.br
.ti -1c
.RI "int \fBRows\fP"
.br
.ti -1c
.RI "int \fBCols\fP"
.br
.ti -1c
.RI "int \fBCurrentIdx\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBFrameRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBGridRect\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCellSize\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImPlotAlignmentData\fP > \fBRowAlignmentData\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImPlotAlignmentData\fP > \fBColAlignmentData\fP"
.br
.ti -1c
.RI "\fBImVector\fP< float > \fBRowRatios\fP"
.br
.ti -1c
.RI "\fBImVector\fP< float > \fBColRatios\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImPlotRange\fP > \fBRowLinkData\fP"
.br
.ti -1c
.RI "\fBImVector\fP< \fBImPlotRange\fP > \fBColLinkData\fP"
.br
.ti -1c
.RI "float \fBTempSizes\fP [2]"
.br
.ti -1c
.RI "bool \fBFrameHovered\fP"
.br
.ti -1c
.RI "bool \fBHasTitle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
