.TH "ImPlot::GetterOverrideX< _Getter >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::GetterOverrideX< _Getter >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetterOverrideX\fP (_Getter getter, double x)"
.br
.ti -1c
.RI "template<typename I > IMPLOT_INLINE \fBImPlotPoint\fP \fBoperator()\fP (I idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _Getter \fBGetter\fP"
.br
.ti -1c
.RI "const double \fBX\fP"
.br
.ti -1c
.RI "const int \fBCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
