.TH "ImPlot::Transformer1" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::Transformer1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformer1\fP (double pixMin, double pltMin, double pltMax, double m, double scaMin, double scaMax, ImPlotTransform fwd, void *data)"
.br
.ti -1c
.RI "template<typename T > IMPLOT_INLINE float \fBoperator()\fP (T p) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBScaMin\fP"
.br
.ti -1c
.RI "double \fBScaMax\fP"
.br
.ti -1c
.RI "double \fBPltMin\fP"
.br
.ti -1c
.RI "double \fBPltMax\fP"
.br
.ti -1c
.RI "double \fBPixMin\fP"
.br
.ti -1c
.RI "double \fBM\fP"
.br
.ti -1c
.RI "ImPlotTransform \fBTransformFwd\fP"
.br
.ti -1c
.RI "void * \fBTransformData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
