.TH "ImPlot::RendererBase" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::RendererBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBImPlot::RendererBarsFillH< _Getter1, _Getter2 >\fP, \fBImPlot::RendererBarsFillV< _Getter1, _Getter2 >\fP, \fBImPlot::RendererBarsLineH< _Getter1, _Getter2 >\fP, \fBImPlot::RendererBarsLineV< _Getter1, _Getter2 >\fP, \fBImPlot::RendererLineSegments1< _Getter >\fP, \fBImPlot::RendererLineSegments2< _Getter1, _Getter2 >\fP, \fBImPlot::RendererLineStrip< _Getter >\fP, \fBImPlot::RendererLineStripSkip< _Getter >\fP, \fBImPlot::RendererMarkersFill< _Getter >\fP, \fBImPlot::RendererMarkersLine< _Getter >\fP, \fBImPlot::RendererRectC< _Getter >\fP, \fBImPlot::RendererShaded< _Getter1, _Getter2 >\fP, \fBImPlot::RendererStairsPost< _Getter >\fP, \fBImPlot::RendererStairsPostShaded< _Getter >\fP, \fBImPlot::RendererStairsPre< _Getter >\fP, and \fBImPlot::RendererStairsPreShaded< _Getter >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRendererBase\fP (int prims, int idx_consumed, int vtx_consumed)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBPrims\fP"
.br
.ti -1c
.RI "\fBTransformer2\fP \fBTransformer\fP"
.br
.ti -1c
.RI "const int \fBIdxConsumed\fP"
.br
.ti -1c
.RI "const int \fBVtxConsumed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
