.TH "ImPlotNextPlotData" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotNextPlotData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImPlotCond \fBRangeCond\fP [ImAxis_COUNT]"
.br
.ti -1c
.RI "\fBImPlotRange\fP \fBRange\fP [ImAxis_COUNT]"
.br
.ti -1c
.RI "bool \fBHasRange\fP [ImAxis_COUNT]"
.br
.ti -1c
.RI "bool \fBFit\fP [ImAxis_COUNT]"
.br
.ti -1c
.RI "double * \fBLinkedMin\fP [ImAxis_COUNT]"
.br
.ti -1c
.RI "double * \fBLinkedMax\fP [ImAxis_COUNT]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
