.TH "ImPlotPointError" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotPointError
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImPlotPointError\fP (double x, double y, double neg, double pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBX\fP"
.br
.ti -1c
.RI "double \fBY\fP"
.br
.ti -1c
.RI "double \fBNeg\fP"
.br
.ti -1c
.RI "double \fBPos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
