.TH "ImPlot::GetterError< T >" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::GetterError< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetterError\fP (const T *xs, const T *ys, const T *neg, const T *pos, int count, int offset, int stride)"
.br
.ti -1c
.RI "template<typename I > IMPLOT_INLINE \fBImPlotPointError\fP \fBoperator()\fP (I idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const T *const \fBXs\fP"
.br
.ti -1c
.RI "const T *const \fBYs\fP"
.br
.ti -1c
.RI "const T *const \fBNeg\fP"
.br
.ti -1c
.RI "const T *const \fBPos\fP"
.br
.ti -1c
.RI "const int \fBCount\fP"
.br
.ti -1c
.RI "const int \fBOffset\fP"
.br
.ti -1c
.RI "const int \fBStride\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
