.TH "ImPlot::IndexerAdd< _Indexer1, _Indexer2 >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::IndexerAdd< _Indexer1, _Indexer2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexerAdd\fP (const _Indexer1 &indexer1, const _Indexer2 &indexer2, double scale1=1, double scale2=1)"
.br
.ti -1c
.RI "template<typename I > IMPLOT_INLINE double \fBoperator()\fP (I idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _Indexer1 & \fBIndexer1\fP"
.br
.ti -1c
.RI "const _Indexer2 & \fBIndexer2\fP"
.br
.ti -1c
.RI "double \fBScale1\fP"
.br
.ti -1c
.RI "double \fBScale2\fP"
.br
.ti -1c
.RI "int \fBCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
