.TH "ImPlot::GetterFuncPtr" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::GetterFuncPtr \- Interprets a user's function pointer as ImPlotPoints\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetterFuncPtr\fP (ImPlotGetter getter, void *data, int count)"
.br
.ti -1c
.RI "template<typename I > IMPLOT_INLINE \fBImPlotPoint\fP \fBoperator()\fP (I idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImPlotGetter \fBGetter\fP"
.br
.ti -1c
.RI "void *const \fBData\fP"
.br
.ti -1c
.RI "const int \fBCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interprets a user's function pointer as ImPlotPoints\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
