.TH "ImPlot::RectC" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::RectC
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImPlotPoint\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImPlotPoint\fP \fBHalfSize\fP"
.br
.ti -1c
.RI "ImU32 \fBColor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
