.TH "ImPlot::Transformer2" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlot::Transformer2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformer2\fP (const \fBImPlotAxis\fP &x_axis, const \fBImPlotAxis\fP &y_axis)"
.br
.ti -1c
.RI "\fBTransformer2\fP (const \fBImPlotPlot\fP &plot)"
.br
.ti -1c
.RI "template<typename P > IMPLOT_INLINE \fBImVec2\fP \fBoperator()\fP (const P &plt) const"
.br
.ti -1c
.RI "template<typename T > IMPLOT_INLINE \fBImVec2\fP \fBoperator()\fP (T x, T y) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransformer1\fP \fBTx\fP"
.br
.ti -1c
.RI "\fBTransformer1\fP \fBTy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
