.TH "ImPlotPoint" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImPlotPoint
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBImPlotPoint\fP (double _x, double _y)"
.br
.ti -1c
.RI "constexpr \fBImPlotPoint\fP (const \fBImVec2\fP &p)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (size_t idx)"
.br
.ti -1c
.RI "double \fBoperator[]\fP (size_t idx) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
