.TH "ImTriangulatorNodeSpan" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImTriangulatorNodeSpan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpush_back\fP (\fBImTriangulatorNode\fP *node)"
.br
.ti -1c
.RI "void \fBfind_erase_unsorted\fP (int idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImTriangulatorNode\fP ** \fBData\fP = NULL"
.br
.ti -1c
.RI "int \fBSize\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
