.TH "ImTriangulatorNode" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImTriangulatorNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUnlink\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImTriangulatorNodeType \fBType\fP"
.br
.ti -1c
.RI "int \fBIndex\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImTriangulatorNode\fP * \fBNext\fP"
.br
.ti -1c
.RI "\fBImTriangulatorNode\fP * \fBPrev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
