.TH "Input::KeybindSet" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input::KeybindSet \- Main class containing keybind data and options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <KeybindSet\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCategory\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCategory\fP > \fBcategories\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main class containing keybind data and options\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
