.TH "Input::KeybindSet::Category" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input::KeybindSet::Category
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAction\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::vector< \fBAction\fP > \fBactions\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
