.TH "Input::InputListener" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input::InputListener \- Listens for input and invokes keybind functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InputListener\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle_input\fP (float dt)"
.br
.ti -1c
.RI "void \fBhandle_bind\fP (const \fBKeybindSet::Category::Action::Bind\fP &bind, float dt)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBKeybindSet\fP * > \fBkeybind_sets\fP = { }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Listens for input and invokes keybind functions\&. 


.PP
\fBSee also\fP
.RS 4
\fBKeybindSet\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
