.TH "InteractionHandler" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InteractionHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle_interaction\fP (\fBPhysicalComponent\fP *obj1, \fBPhysicalComponent\fP *obj2, float dt) noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
