.TH "DirectX::Keyboard::Impl" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::Keyboard::Impl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImpl\fP (\fBKeyboard\fP *owner)"
.br
.ti -1c
.RI "\fBImpl\fP (\fBImpl\fP &&)=default"
.br
.ti -1c
.RI "\fBImpl\fP & \fBoperator=\fP (\fBImpl\fP &&)=default"
.br
.ti -1c
.RI "\fBImpl\fP (\fBImpl\fP const &)=delete"
.br
.ti -1c
.RI "\fBImpl\fP & \fBoperator=\fP (\fBImpl\fP const &)=delete"
.br
.ti -1c
.RI "void \fBGetState\fP (\fBState\fP &state) const"
.br
.ti -1c
.RI "void \fBReset\fP () noexcept"
.br
.ti -1c
.RI "bool \fBIsConnected\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBState\fP \fBmState\fP"
.br
.ti -1c
.RI "\fBKeyboard\fP * \fBmOwner\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBKeyboard::Impl\fP * \fBs_keyboard\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
