.TH "MakeSpriteFont.IFontImporter" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.IFontImporter
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMakeSpriteFont\&.BitmapImporter\fP, and \fBMakeSpriteFont\&.TrueTypeImporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBImport\fP (\fBCommandLineOptions\fP options)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< \fBGlyph\fP > \fBGlyphs\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBLineSpacing\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
