.TH "MakeSpriteFont.Glyph" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.Glyph
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlyph\fP (char character, Bitmap bitmap, Rectangle? subrect=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBCharacter\fP"
.br
.ti -1c
.RI "Bitmap \fBBitmap\fP"
.br
.ti -1c
.RI "Rectangle \fBSubrect\fP"
.br
.ti -1c
.RI "float \fBXOffset\fP"
.br
.ti -1c
.RI "float \fBYOffset\fP"
.br
.ti -1c
.RI "float \fBXAdvance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
