.TH "MakeSpriteFont" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBitmapImporter\fP"
.br
.ti -1c
.RI "class \fBBitmapUtils\fP"
.br
.ti -1c
.RI "class \fBCharacterRegion\fP"
.br
.ti -1c
.RI "class \fBCharacterRegionTypeConverter\fP"
.br
.ti -1c
.RI "class \fBCommandLineOptions\fP"
.br
.ti -1c
.RI "class \fBCommandLineParser\fP"
.br
.ti -1c
.RI "class \fBGlyph\fP"
.br
.ti -1c
.RI "class \fBGlyphCropper\fP"
.br
.ti -1c
.RI "class \fBGlyphPacker\fP"
.br
.ti -1c
.RI "interface \fBIFontImporter\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBSpriteFontWriter\fP"
.br
.ti -1c
.RI "class \fBTrueTypeImporter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTextureFormat\fP { \fBAuto\fP, \fBRgba32\fP, \fBBgra4444\fP, \fBCompressedMono\fP }"
.br
.ti -1c
.RI "enum \fBFeatureLevel\fP { \fBFL9_1\fP, \fBFL9_2\fP, \fBFL9_3\fP, \fBFL10_0\fP, \fBFL10_1\fP, \fBFL11_0\fP, \fBFL11_1\fP, \fBFL12_0\fP, \fBFL12_1\fP, \fBFL12_2\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
