.TH "MakeSpriteFont.CommandLineOptions" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.CommandLineOptions
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBSourceFont\fP"
.br
.ti -1c
.RI "string \fBOutputFile\fP"
.br
.ti -1c
.RI "readonly List< \fBCharacterRegion\fP > \fBCharacterRegions\fP = new List<\fBCharacterRegion\fP>()"
.br
.ti -1c
.RI "readonly int \fBDefaultCharacter\fP = 0"
.br
.ti -1c
.RI "float \fBFontSize\fP = 23"
.br
.ti -1c
.RI "FontStyle \fBFontStyle\fP = FontStyle\&.Regular"
.br
.ti -1c
.RI "float \fBLineSpacing\fP = 0"
.br
.ti -1c
.RI "float \fBCharacterSpacing\fP = 0"
.br
.ti -1c
.RI "bool \fBSharp\fP = false"
.br
.ti -1c
.RI "TextureFormat \fBTextureFormat\fP = TextureFormat\&.Auto"
.br
.ti -1c
.RI "bool \fBNoPremultiply\fP = false"
.br
.ti -1c
.RI "string \fBDebugOutputSpriteSheet\fP = null"
.br
.ti -1c
.RI "FeatureLevel \fBFeatureLevel\fP = FeatureLevel\&.FL9_1"
.br
.ti -1c
.RI "bool \fBFastPack\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
