.TH "MakeSpriteFont.CharacterRegion" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.CharacterRegion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCharacterRegion\fP (char start, char end)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static IEnumerable< Char > \fBFlatten\fP (IEnumerable< \fBCharacterRegion\fP > regions)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBStart\fP"
.br
.ti -1c
.RI "char \fBEnd\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< Char > \fBCharacters\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
