.TH "MakeSpriteFont.BitmapImporter" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.BitmapImporter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMakeSpriteFont\&.IFontImporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBImport\fP (\fBCommandLineOptions\fP options)"
.br
.in -1c
.in +1c
.ti -1c
.RI "void \fBImport\fP (\fBCommandLineOptions\fP options)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< \fBGlyph\fP > \fBGlyphs\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBLineSpacing\fP\fC [get]\fP"
.br
.in -1c

Properties inherited from \fBMakeSpriteFont\&.IFontImporter\fP
.in +1c
.ti -1c
.RI "IEnumerable< \fBGlyph\fP > \fBGlyphs\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBLineSpacing\fP\fC [get]\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MakeSpriteFont\&.BitmapImporter\&.Import (\fBCommandLineOptions\fP options)\fC [inline]\fP"

.PP
Implements \fBMakeSpriteFont\&.IFontImporter\fP\&.
.SH "Property Documentation"
.PP 
.SS "IEnumerable<\fBGlyph\fP> MakeSpriteFont\&.BitmapImporter\&.Glyphs\fC [get]\fP"

.PP
Implements \fBMakeSpriteFont\&.IFontImporter\fP\&.
.SS "float MakeSpriteFont\&.BitmapImporter\&.LineSpacing\fC [get]\fP"

.PP
Implements \fBMakeSpriteFont\&.IFontImporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
