.TH "MakeSpriteFont.CommandLineParser" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.CommandLineParser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNameAttribute\fP"
.br
.ti -1c
.RI "class \fBRequiredAttribute\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandLineParser\fP (object optionsObject)"
.br
.ti -1c
.RI "bool \fBParseCommandLine\fP (string[] args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
