.TH "MakeSpriteFont.CharacterRegionTypeConverter" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.CharacterRegionTypeConverter
.SH SYNOPSIS
.br
.PP
.PP
Inherits TypeConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBCanConvertFrom\fP (ITypeDescriptorContext context, Type sourceType)"
.br
.ti -1c
.RI "override object \fBConvertFrom\fP (ITypeDescriptorContext context, CultureInfo culture, object value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
