.TH "MakeSpriteFont.BitmapUtils.PixelAccessor" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakeSpriteFont.BitmapUtils.PixelAccessor
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPixelAccessor\fP (Bitmap bitmap, ImageLockMode mode, Rectangle? region=null)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Rectangle \fBRegion\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBthis[int x, int y]\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
