.TH "Material::MaterialData" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Material::MaterialData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMaterialData\fP &data) const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColor\fP \fBks\fP = \fBColor\fP(0, 0, 0, 255)"
.br
.ti -1c
.RI "\fBColor\fP \fBkd\fP = \fBColor\fP(255, 255, 255, 255)"
.br
.ti -1c
.RI "\fBColor\fP \fBka\fP = \fBColor\fP(0, 0, 0, 255)"
.br
.ti -1c
.RI "float \fBa\fP = 0\&.5f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
