.TH "Material" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Material \- \fBMaterial\fP data for rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Material\&.h>\fP
.PP
Inherits \fBGraphicsTracker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterial\fP (const \fBMaterial\fP &mat)"
.br
.ti -1c
.RI "\fBMaterial\fP (const std::string &file)"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "void \fBset_data\fP (const std::string &file)"
.br
.ti -1c
.RI "void \fBset_data\fP (const \fBMaterial\fP &material)"
.br
.ti -1c
.RI "bool \fBhas_texture\fP () const noexcept"
.br
.ti -1c
.RI "bool \fBhas_normal_map\fP () const noexcept"
.br
.ti -1c
.RI "bool \fBhas_environment_texture\fP () const noexcept"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBMaterial\fP &material) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMaterial\fP &material) const noexcept"
.br
.ti -1c
.RI "\fBTexture\fP & \fBget_albedo_texture\fP ()"
.br
.ti -1c
.RI "\fBTexture\fP & \fBget_normal_map\fP ()"
.br
.ti -1c
.RI "\fBTexture\fP & \fBget_environment_texture\fP ()"
.br
.ti -1c
.RI "\fBColor\fP \fBget_albedo\fP () const"
.br
.ti -1c
.RI "void \fBset_albedo\fP (const \fBColor\fP &albedo)"
.br
.ti -1c
.RI "\fBColor\fP \fBget_specular\fP () const"
.br
.ti -1c
.RI "void \fBset_specular\fP (const \fBColor\fP &specular)"
.br
.ti -1c
.RI "\fBColor\fP \fBget_ambient\fP () const"
.br
.ti -1c
.RI "void \fBset_ambient\fP (const \fBColor\fP &ambient)"
.br
.ti -1c
.RI "float \fBget_shininess\fP () const"
.br
.ti -1c
.RI "void \fBset_shininess\fP (float shininess)"
.br
.in -1c

Public Member Functions inherited from \fBGraphicsTracker\fP
.in +1c
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool changed) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGraphicsPipeline\fP \fBpipeline\fP {}"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBGraphicsTracker\fP
.in +1c
.ti -1c
.RI "bool \fBchanged\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMaterial\fP data for rendering\&. 

Specifies how light interacts with the object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
