.TH "Mesh" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mesh \- A mesh for collision and rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP (const std::vector< \fBVertex\fP > &vertices, const std::vector< UINT > &indices)"
.br
.ti -1c
.RI "\fBMesh\fP (const std::vector< \fBVertex\fP > &vertices)"
.br
.ti -1c
.RI "\fBMesh\fP (const std::string &file)"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMesh\fP &mesh) const noexcept"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBMesh\fP &mesh) noexcept"
.br
.ti -1c
.RI "GET \fBSimpleBox\fP \fBget_bounding_box\fP () const noexcept"
.br
.ti -1c
.RI "GET const std::vector< \fBVertex\fP > & \fBget_vertices\fP () const noexcept"
.br
.ti -1c
.RI "GET const std::vector< \fBTriangle\fP > & \fBget_triangles\fP () const noexcept"
.br
.ti -1c
.RI "GET const std::vector< \fBSimpleVertex\fP > & \fBget_physics_vertices\fP () const noexcept"
.br
.ti -1c
.RI "GET const std::vector< \fBSimpleTriangle\fP > & \fBget_physics_triangles\fP () const noexcept"
.br
.ti -1c
.RI "void \fBset_vertices\fP (const std::vector< \fBVertex\fP > &new_verts, size_t physics_verts_chunk_divisor=3)"
.br
.RI "Sets current vertices to new vertices\&. "
.ti -1c
.RI "void \fBset_vertices\fP (const std::string &file, size_t physics_verts_chunk_divisor=3)"
.br
.RI "Sets current vertices to new vertices by reading a file\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< UINT > \fBindices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A mesh for collision and rendering\&. 

Contains a model's geometric data\&. 
.PP
\fBSee also\fP
.RS 4
\fBVertex\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Mesh::compile ()"
*verts[i+0]\&.bitangent = bitangent;
.SS "void Mesh::set_vertices (const std::string & file, size_t physics_verts_chunk_divisor = \fC3\fP)"

.PP
Sets current vertices to new vertices by reading a file\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_verts\fP New vertices\&. 
.br
\fIphysics_verts_chunk_divisor\fP Index at which to decimate the mesh by for physics optimizations\&. 
.RE
.PP

.SS "void Mesh::set_vertices (const std::vector< \fBVertex\fP > & new_verts, size_t physics_verts_chunk_divisor = \fC3\fP)"

.PP
Sets current vertices to new vertices\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_verts\fP New vertices\&. 
.br
\fIphysics_verts_chunk_divisor\fP Index at which to decimate the mesh by for physics optimizations\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
