.TH "MyImPlot::WaveData" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyImPlot::WaveData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWaveData\fP (double x, double amp, double freq, double offset)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBX\fP"
.br
.ti -1c
.RI "double \fBAmp\fP"
.br
.ti -1c
.RI "double \fBFreq\fP"
.br
.ti -1c
.RI "double \fBOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
