.TH "OverlapEventInfo" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OverlapEventInfo
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOverlapEventObject\fP"
.br
.ti -1c
.RI "struct \fBOverlapInfo\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBoverlapped\fP {false}"
.br
.ti -1c
.RI "struct \fBOverlapEventInfo::OverlapInfo\fP \fBoverlap_info\fP"
.br
.ti -1c
.RI "std::pair< \fBOverlapEventObject\fP, \fBOverlapEventObject\fP > \fBobjects\fP {std::make_pair(\fBOverlapEventObject\fP{}, \fBOverlapEventObject\fP{})}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
