.TH "OverlapEventInfo::OverlapInfo" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OverlapEventInfo::OverlapInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFVector3\fP \fBpoint_of_overlap\fP {}"
.br
.ti -1c
.RI "\fBFVector3\fP \fBaxis_overlap\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
