.TH "PerFramePSCB" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerFramePSCB
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFVector3\fP \fBcamera_position\fP"
.br
.ti -1c
.RI "UINT \fBdirectional_light_count\fP = 0"
.br
.ti -1c
.RI "UINT \fBpoint_light_count\fP = 0"
.br
.ti -1c
.RI "UINT \fBspotlight_count\fP = 0"
.br
.ti -1c
.RI "DXDLData \fBdirectional_lights\fP [MAX_LIGHTS_PER_TYPE] = { }"
.br
.ti -1c
.RI "DXPLData \fBpoint_lights\fP [MAX_LIGHTS_PER_TYPE] = { }"
.br
.ti -1c
.RI "DXSLData \fBspotlights\fP [MAX_LIGHTS_PER_TYPE] = { }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
