.TH "PointLightComponent" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointLightComponent \- \fBComponent\fP for a point light\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PointLightComponent\&.h>\fP
.PP
Inherits \fBLightComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPointLightComponent\fP &component) const noexcept"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBPointLightComponent\fP &light) noexcept"
.br
.ti -1c
.RI "float \fBget_range\fP () const noexcept"
.br
.ti -1c
.RI "void \fBset_range\fP (float range) noexcept"
.br
.ti -1c
.RI "\fBFVector3\fP \fBget_attenuation\fP () const noexcept"
.br
.ti -1c
.RI "void \fBset_attenuation\fP (\fBFVector3\fP attenuation) noexcept"
.br
.in -1c

Public Member Functions inherited from \fBLightComponent\fP
.in +1c
.ti -1c
.RI "\fBLightComponent\fP (Type type)"
.br
.ti -1c
.RI "\fBColor\fP \fBget_albedo\fP () const noexcept"
.br
.ti -1c
.RI "void \fBset_albedo\fP (const \fBColor\fP &albedo)"
.br
.ti -1c
.RI "\fBColor\fP \fBget_specular\fP () const noexcept"
.br
.ti -1c
.RI "void \fBset_specular\fP (const \fBColor\fP &specular)"
.br
.ti -1c
.RI "bool \fBis_null\fP () const noexcept"
.br
.ti -1c
.RI "void \fBis_null\fP (bool null) noexcept"
.br
.in -1c

Public Member Functions inherited from \fBGraphicsComponent\fP
.in +1c
.ti -1c
.RI "\fBGraphicsComponent\fP (Type type)"
.br
.ti -1c
.RI "virtual void \fBset_position\fP (\fBFVector3\fP position) noexcept override"
.br
.ti -1c
.RI "virtual void \fBset_rotation\fP (\fBFVector3\fP rotation) noexcept"
.br
.ti -1c
.RI "virtual void \fBset_size\fP (\fBFVector3\fP size) noexcept"
.br
.in -1c

Public Member Functions inherited from \fBComponent\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP (const Type &type)"
.br
.ti -1c
.RI "virtual void \fBset_position\fP (\fBFVector3\fP position) noexcept"
.br
.ti -1c
.RI "virtual void \fBset_rotation\fP (\fBFVector3\fP rotation) noexcept"
.br
.ti -1c
.RI "virtual void \fBset_size\fP (\fBFVector3\fP size) noexcept"
.br
.ti -1c
.RI "virtual void \fBtranslate\fP (\fBFVector3\fP position) noexcept"
.br
.ti -1c
.RI "virtual void \fBrotate\fP (\fBFVector3\fP rotation) noexcept"
.br
.ti -1c
.RI "virtual void \fBsize\fP (\fBFVector3\fP size) noexcept"
.br
.ti -1c
.RI "virtual GET \fBFVector3\fP \fBget_position\fP () const noexcept"
.br
.ti -1c
.RI "virtual GET \fBFVector3\fP \fBget_rotation\fP () const noexcept"
.br
.ti -1c
.RI "virtual GET \fBFVector3\fP \fBget_size\fP () const noexcept"
.br
.ti -1c
.RI "virtual void \fBset_transform\fP (\fBTransform\fP transform) noexcept"
.br
.ti -1c
.RI "virtual GET \fBTransform\fP \fBget_transform\fP () const noexcept"
.br
.ti -1c
.RI "GET Type \fBget_type\fP () const noexcept"
.br
.ti -1c
.RI "virtual bool \fBoperator==\fP (const \fBComponent\fP &component) const noexcept"
.br
.ti -1c
.RI "virtual void \fBoperator=\fP (const \fBComponent\fP &component) noexcept"
.br
.in -1c

Public Member Functions inherited from \fBControllable\fP
.in +1c
.ti -1c
.RI "virtual void \fBbase_clean_up\fP ()"
.br
.ti -1c
.RI "virtual void \fBbase_compile\fP ()"
.br
.ti -1c
.RI "virtual void \fBbase_tick\fP (float dt)"
.br
.ti -1c
.RI "virtual void \fBpre_scene_compile\fP ()"
.br
.ti -1c
.RI "virtual void \fBpost_scene_compile\fP ()"
.br
.ti -1c
.RI "virtual void \fBclean_up\fP ()"
.br
.ti -1c
.RI "virtual void \fBcompile\fP ()"
.br
.ti -1c
.RI "virtual void \fBtick\fP (float dt)"
.br
.in -1c

Public Member Functions inherited from \fBGraphicsTracker\fP
.in +1c
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool changed) noexcept"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const Type \fBcomponent_type\fP = Type::PointLightComponent"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBComponent\fP
.in +1c
.ti -1c
.RI "enum class \fBType\fP { \fBNone\fP, \fBStaticMeshComponent\fP, \fBCameraComponent\fP, \fBDirectionalLightComponent\fP, \fBPointLightComponent\fP, \fBSpotlightComponent\fP, \fBBoxComponent\fP, \fBSkyComponent\fP, \fBMaterialComponent\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBLightComponent\fP
.in +1c
.ti -1c
.RI "template<ACCEPT_BASE_AND_HEIRS_ONLY(typename T, \fBComponent\fP) > static bool \fBis_light_component\fP (const T &component)"
.br
.in -1c

Static Public Member Functions inherited from \fBGraphicsComponent\fP
.in +1c
.ti -1c
.RI "template<ACCEPT_BASE_AND_HEIRS_ONLY(typename T, \fBComponent\fP) > static bool \fBis_graphics_component\fP (const T &component)"
.br
.in -1c

Public Attributes inherited from \fBComponent\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP * \fBparent\fP = nullptr"
.br
.in -1c

Protected Member Functions inherited from \fBLightComponent\fP
.in +1c
.ti -1c
.RI "void \fBrender_editor_gui_section\fP () override"
.br
.ti -1c
.RI "virtual void \fBrender_light_component_editor_gui_section\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBComponent\fP
.in +1c
.ti -1c
.RI "void \fBbase_render_editor_gui_section\fP ()"
.br
.ti -1c
.RI "virtual void \fBrender_editor_gui_section\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBLightComponent\fP
.in +1c
.ti -1c
.RI "\fBColor\fP \fBalbedo\fP = \fBColor\fP(255, 255, 255, 255)"
.br
.ti -1c
.RI "\fBColor\fP \fBspecular\fP = \fBColor\fP(50, 50, 50, 255)"
.br
.ti -1c
.RI "bool \fBnull\fP = false"
.br
.in -1c

Protected Attributes inherited from \fBComponent\fP
.in +1c
.ti -1c
.RI "\fBTransform\fP \fBtransform\fP"
.br
.ti -1c
.RI "Type \fBtype\fP = Type::None"
.br
.in -1c

Protected Attributes inherited from \fBGraphicsTracker\fP
.in +1c
.ti -1c
.RI "bool \fBchanged\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBComponent\fP for a point light\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
