.TH "ReadObjFileDataOutput" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadObjFileDataOutput
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadObjFileDataOutput\fP (size_t vio, size_t tcio, size_t nio)"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBReadObjFileDataOutput\fP &lhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBvertex_index_offset\fP = 0"
.br
.ti -1c
.RI "size_t \fBtexcoord_index_offset\fP = 0"
.br
.ti -1c
.RI "size_t \fBnormal_index_offset\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
