.TH "ReadObjFileDataInput" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadObjFileDataInput
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadObjFileDataInput\fP (std::vector< std::string > contents, \fBReadObjFileDataOutput\fP offsets=\fBReadObjFileDataOutput\fP(), std::wstring file_name=L'')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBcontents\fP"
.br
.ti -1c
.RI "\fBReadObjFileDataOutput\fP \fBoffsets\fP"
.br
.ti -1c
.RI "std::wstring \fBfile_name\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
