.TH "RenderingStaticMesh" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderingStaticMesh \- Graphics-side static mesh\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsScene\&.h>\fP
.PP
Inherits \fBRenderingComponent< StaticMeshComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderingStaticMesh\fP (\fBStaticMeshComponent\fP *smc)"
.br
.ti -1c
.RI "bool \fBupdate\fP (\fBRenderingCamera\fP &camera)"
.br
.ti -1c
.RI "void \fBupdate_lights\fP (const std::vector< \fBRenderingDirectionalLight\fP > &dl, const std::vector< \fBRenderingPointLight\fP > &pl, const std::vector< \fBRenderingSpotlight\fP > &sl)"
.br
.ti -1c
.RI "void \fBcompile\fP (\fBRenderingCamera\fP &camera)"
.br
.ti -1c
.RI "void \fBset_resources\fP (\fBRenderingCamera\fP &camera)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBRenderingComponent< StaticMeshComponent >\fP
.in +1c
.ti -1c
.RI "\fBRenderingComponent\fP (\fBStaticMeshComponent\fP *component)"
.br
.ti -1c
.RI "bool \fBneeds_compile\fP () const noexcept"
.br
.ti -1c
.RI "void \fBneeds_compile\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBvalid\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRenderingMaterial\fP \fBmaterial\fP {}"
.br
.ti -1c
.RI "\fBRootConstantsContainer\fP< VSWVPConstants > \fBwvp_data\fP {}"
.br
.ti -1c
.RI "\fBRootConstantsContainer\fP< PSCameraConstants > \fBpos_data\fP {}"
.br
.ti -1c
.RI "\fBRootConstantsContainer\fP< VSTransformConstants > \fBtransform_data\fP {}"
.br
.ti -1c
.RI "\fBConstantBufferContainer\fP< PSLightsCB > \fBlights_data\fP {}"
.br
.ti -1c
.RI "bool \fBupdate_lights_signal\fP = false"
.br
.in -1c

Public Attributes inherited from \fBRenderingComponent< StaticMeshComponent >\fP
.in +1c
.ti -1c
.RI "\fBStaticMeshComponent\fP * \fBcomponent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graphics-side static mesh\&. 


.PP
\fBSee also\fP
.RS 4
\fBStaticMeshComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
