.TH "RenderingComponent<>" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderingComponent<> \- Each graphics component has thir graphics-side counterpart\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsScene\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderingComponent\fP (T *component)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (T component)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T * \fBcomponent\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<ACCEPT_BASE_AND_HEIRS_ONLY(typename T, \fBGraphicsComponent\fP)>
.br
class RenderingComponent<>"Each graphics component has thir graphics-side counterpart\&. 

Graphics-side component base class\&. 
.PP
\fBSee also\fP
.RS 4
\fBGraphicsComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
