.TH "RenderingSpotlight" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderingSpotlight \- Graphics-side spotlight\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsScene\&.h>\fP
.PP
Inherits \fBRenderingComponent< SpotlightComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderingSpotlight\fP (\fBSpotlightComponent\fP *light)"
.br
.ti -1c
.RI "bool \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBRenderingComponent< SpotlightComponent >\fP
.in +1c
.ti -1c
.RI "\fBRenderingComponent\fP (\fBSpotlightComponent\fP *component)"
.br
.ti -1c
.RI "bool \fBneeds_compile\fP () const noexcept"
.br
.ti -1c
.RI "void \fBneeds_compile\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBvalid\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RenderingSpotlightData \fBdata\fP {}"
.br
.in -1c

Public Attributes inherited from \fBRenderingComponent< SpotlightComponent >\fP
.in +1c
.ti -1c
.RI "\fBSpotlightComponent\fP * \fBcomponent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graphics-side spotlight\&. 


.PP
\fBSee also\fP
.RS 4
\fBSpotlightComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
