.TH "RenderingComponent< T >" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderingComponent< T > \- Each graphics component has thir graphics-side counterpart\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsScene\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderingComponent\fP (T *component)"
.br
.ti -1c
.RI "bool \fBneeds_compile\fP () const noexcept"
.br
.ti -1c
.RI "void \fBneeds_compile\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBvalid\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T * \fBcomponent\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
requires std::derived_from<T, \fBGraphicsTracker\fP>
.br
class RenderingComponent< T >"Each graphics component has thir graphics-side counterpart\&. 

Graphics-side component base class\&. 
.PP
\fBSee also\fP
.RS 4
\fBGraphicsComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
