.TH "RenderingStaticMesh" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderingStaticMesh \- Graphics-side static mesh\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsScene\&.h>\fP
.PP
Inherits \fBRenderingComponent< StaticMeshComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderingStaticMesh\fP (\fBStaticMeshComponent\fP *smc)"
.br
.ti -1c
.RI "bool \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBupdate_lights\fP (const std::vector< \fBRenderingDirectionalLight\fP > &dl, const std::vector< \fBRenderingPointLight\fP > &pl, const std::vector< \fBRenderingSpotlight\fP > &sl)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBStaticMeshComponent\fP component)"
.br
.in -1c

Public Member Functions inherited from \fBRenderingComponent< StaticMeshComponent >\fP
.in +1c
.ti -1c
.RI "\fBRenderingComponent\fP (T *component)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (T component)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::ConstantBufferContainer\fP< PSMaterialCB > \fBmaterial_data\fP = PSMaterialCB{}"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::ConstantBufferContainer\fP< PSLightsCB > \fBlights_data\fP = PSLightsCB{}"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::RootConstantsContainer\fP< VSTransformConstants > \fBtransform_data\fP = VSTransformConstants{}"
.br
.in -1c

Public Attributes inherited from \fBRenderingComponent< StaticMeshComponent >\fP
.in +1c
.ti -1c
.RI "T * \fBcomponent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graphics-side static mesh\&. 


.PP
\fBSee also\fP
.RS 4
\fBStaticMeshComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
