.TH "RenderingMaterial" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderingMaterial \- Graphics-side material\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GraphicsScene\&.h>\fP
.PP
Inherits \fBRenderingComponent< Material >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderingMaterial\fP (\fBMaterial\fP *mat)"
.br
.ti -1c
.RI "bool \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "void \fBset_resources\fP ()"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBRenderingComponent< Material >\fP
.in +1c
.ti -1c
.RI "\fBRenderingComponent\fP (\fBMaterial\fP *component)"
.br
.ti -1c
.RI "bool \fBneeds_compile\fP () const noexcept"
.br
.ti -1c
.RI "void \fBneeds_compile\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool b) noexcept"
.br
.ti -1c
.RI "bool \fBvalid\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShaderResourceViewContainer\fP \fBalbedo_texture\fP {}"
.br
.ti -1c
.RI "\fBShaderResourceViewContainer\fP \fBnormal_map\fP {}"
.br
.ti -1c
.RI "\fBShaderResourceViewContainer\fP \fBspecular_map\fP {}"
.br
.ti -1c
.RI "\fBConstantBufferContainer\fP< PSMaterialCB > \fBmaterial_data\fP {}"
.br
.in -1c

Public Attributes inherited from \fBRenderingComponent< Material >\fP
.in +1c
.ti -1c
.RI "\fBMaterial\fP * \fBcomponent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Graphics-side material\&. 


.PP
\fBSee also\fP
.RS 4
\fBMaterial\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
