.TH "RenderingSky" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderingSky
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenderingComponent< SkyComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderingSky\fP (\fBSkyComponent\fP *sky)"
.br
.ti -1c
.RI "bool \fBupdate\fP (\fBFVector3\fP camera_pos)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBSkyComponent\fP component)"
.br
.in -1c

Public Member Functions inherited from \fBRenderingComponent< SkyComponent >\fP
.in +1c
.ti -1c
.RI "\fBRenderingComponent\fP (T *component)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (T component)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::ConstantBufferContainer\fP< PSSkyCB > \fBdata\fP = PSSkyCB{}"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::RootConstantsContainer\fP< VSTransformConstants > \fBtransform_data\fP = VSTransformConstants{}"
.br
.in -1c

Public Attributes inherited from \fBRenderingComponent< SkyComponent >\fP
.in +1c
.ti -1c
.RI "T * \fBcomponent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
