.TH "Scene" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene \- \fBScene\fP to store objects in\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP (\fBGraphicsScene\fP *graphics_scene)"
.br
.ti -1c
.RI "void \fBtick\fP (float dt)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "GET std::set< \fBObject\fP * > \fBget_objects\fP () const noexcept"
.br
.ti -1c
.RI "\fBObject\fP * \fBadd_object\fP (std::unique_ptr< \fBObject\fP > &&object)"
.br
.ti -1c
.RI "\fBCharacter\fP * \fBadd_character\fP (std::unique_ptr< \fBCharacter\fP > &&character)"
.br
.ti -1c
.RI "void \fBrender_editor_gui_section\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGraphicsScene\fP * \fBgraphics_scene\fP {nullptr}"
.br
.ti -1c
.RI "\fBInput::InputListener\fP \fBinput_listener\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBScene\fP to store objects in\&. 


.PP
\fBSee also\fP
.RS 4
\fBGraphicsScene\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
