.TH "Scene" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene \- \fBScene\fP to store objects in\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scene\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP (\fBGraphicsScene\fP *graphics_scene)"
.br
.ti -1c
.RI "void \fBtick\fP (float dt)"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "GET std::vector< std::shared_ptr< \fBObject\fP > > & \fBget_objects\fP () noexcept"
.br
.ti -1c
.RI "void \fBadd_object\fP (const std::shared_ptr< \fBObject\fP > &object) noexcept"
.br
.ti -1c
.RI "void \fBadd_character\fP (const std::shared_ptr< \fBCharacter\fP > &character) noexcept"
.br
.ti -1c
.RI "void \fBremove_object\fP (int index) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGraphicsScene\fP * \fBgraphics_scene\fP = nullptr"
.br
.ti -1c
.RI "\fBInput::InputListener\fP \fBinput_listener\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBScene\fP to store objects in\&. 


.PP
\fBSee also\fP
.RS 4
\fBGraphicsScene\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
