.TH "Shader" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shader \- \fBShader\fP data for rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ShaderCompiler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShader\fP (const std::string &target, const std::string &file_name, std::vector< DxcDefine > defines={})"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const std::string &file)"
.br
.ti -1c
.RI "GET std::string \fBget_target\fP () const noexcept"
.br
.ti -1c
.RI "GET std::string \fBget_entrypoint\fP () const noexcept"
.br
.ti -1c
.RI "GET std::string \fBget_file\fP () const noexcept"
.br
.ti -1c
.RI "GET std::vector< DxcDefine > \fBget_defines\fP () const noexcept"
.br
.ti -1c
.RI "GET ComPtr< IDxcResult > & \fBget_compile_result\fP () noexcept"
.br
.ti -1c
.RI "GET ComPtr< ID3D12ShaderReflection > & \fBget_reflection\fP () noexcept"
.br
.ti -1c
.RI "GET ComPtr< IDxcBlob > \fBget_bytecode_blob\fP () const"
.br
.ti -1c
.RI "GET bool \fBoperator==\fP (const \fBShader\fP &shader) const noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBShader\fP data for rendering\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
