.TH "ShaderStorage" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShaderStorage \- Stores all compiled shaders from graphics pipeline compilation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Storage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShaderStorage\fP (\fBShaderStorage\fP &other)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBShaderStorage\fP &)=delete"
.br
.ti -1c
.RI "GET std::optional< std::weak_ptr< \fBShader\fP > > \fBget_shader\fP (const std::string &file) noexcept"
.br
.ti -1c
.RI "std::weak_ptr< \fBShader\fP > \fBadd_and_compile_shader\fP (const std::string &target, const std::string &file)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GET \fBShaderStorage\fP * \fBget_instance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores all compiled shaders from graphics pipeline compilation\&. 

Prevents shaders from being compiled multiple times for every object that needs it\&. 
.PP
\fBSee also\fP
.RS 4
\fBShader\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
