.TH "SimpleBox" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleBox
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleBox\fP (const std::vector< \fBSimpleVertex\fP > &verts)"
.br
.ti -1c
.RI "std::vector< \fBSimpleTriangle\fP > \fBsplit_into_triangles\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBSimpleVertex\fP > \fBvertices\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
