.TH "SimpleBoundingBox" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleBoundingBox
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFVector3\fP \fBget_min\fP () const"
.br
.ti -1c
.RI "\fBFVector3\fP \fBget_max\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBlength\fP {1\&.0f}"
.br
.ti -1c
.RI "float \fBwidth\fP {1\&.0f}"
.br
.ti -1c
.RI "float \fBheight\fP {1\&.0f}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
