.TH "SimpleBox" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleBox
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleBox\fP (const std::vector< \fBSimpleVertex\fP > &verts)"
.br
.ti -1c
.RI "std::vector< \fBSimpleTriangle\fP > \fBsplit_into_triangles\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::array< \fBSimpleVertex\fP, 8 > \fBvertices\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::array<\fBSimpleVertex\fP, 8> SimpleBox::vertices"
\fBInitial value:\fP.PP
.nf
= {
        SimpleVertex(0\&.0f, 0\&.0f, 0\&.0f),
        SimpleVertex(0\&.0f, 0\&.0f, 1\&.0f),
        SimpleVertex(0\&.0f, 1\&.0f, 0\&.0f),
        SimpleVertex(0\&.0f, 1\&.0f, 1\&.0f),
        SimpleVertex(1\&.0f, 0\&.0f, 0\&.0f),
        SimpleVertex(1\&.0f, 0\&.0f, 1\&.0f),
        SimpleVertex(1\&.0f, 1\&.0f, 0\&.0f),
        SimpleVertex(1\&.0f, 1\&.0f, 1\&.0f)
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
