.TH "SimpleVertex" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleVertex
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleVertex\fP (float x, float y, float z)"
.br
.ti -1c
.RI "\fBSimpleVertex\fP (\fBFVector3\fP position)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSimpleVertex\fP &vertex) const noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSimpleVertex\fP &vertex) const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFVector3\fP \fBposition\fP = \fBFVector3\fP()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
