.TH "DirectX::SoundStreamInstance::Impl::Packets" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectX::SoundStreamInstance::Impl::Packets
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "State \fBstate\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "uint8_t * \fBstitchBuffer\fP"
.br
.ti -1c
.RI "uint32_t \fBvalid\fP"
.br
.ti -1c
.RI "uint32_t \fBaudioBytes\fP"
.br
.ti -1c
.RI "uint32_t \fBstartPosition\fP"
.br
.ti -1c
.RI "OVERLAPPED \fBrequest\fP"
.br
.ti -1c
.RI "\fBBufferNotify\fP \fBnotify\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
