.TH "std::less< DirectX::SimpleMath::Vector2 >" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::less< DirectX::SimpleMath::Vector2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBDirectX::SimpleMath::Vector2\fP &V1, const \fBDirectX::SimpleMath::Vector2\fP &V2) const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
