.TH "Texture" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture \- \fBTexture\fP for rendering onto objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Texture\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTexture\fP (const std::string &file)"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTexture\fP &texture) const noexcept"
.br
.ti -1c
.RI "void \fBset_texture\fP (const std::string &file)"
.br
.ti -1c
.RI "GET std::string \fBget_file\fP () const noexcept"
.br
.ti -1c
.RI "bool \fBexists\fP () const noexcept"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBload_texture\fP (const std::string &file, DirectX::ScratchImage &image, DirectX::ScratchImage &mip_chain)"
.br
.RI "Compile texture file\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DirectX::ScratchImage \fBimage\fP"
.br
.ti -1c
.RI "DirectX::ScratchImage \fBmip_chain\fP"
.br
.ti -1c
.RI "\fBGraphicsPipeline::RootSignature::ShaderResourceView\fP \fBsrv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTexture\fP for rendering onto objects\&. 


.PP
\fBSee also\fP
.RS 4
\fBGraphicsPipeline::RootSignature::ShaderResourceView\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Texture::load_texture (const std::string & file, DirectX::ScratchImage & image, DirectX::ScratchImage & mip_chain)\fC [static]\fP"

.PP
Compile texture file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP Location of file\&. 
.br
\fIimage\fP The image data to write to\&. 
.br
\fImip_chain\fP The mipmap data to write to\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
