.TH "Texture" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture \- \fBTexture\fP for rendering onto objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Texture\&.h>\fP
.PP
Inherits \fBGraphicsTracker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTexture\fP (const \fBTexture\fP &texture)"
.br
.ti -1c
.RI "\fBTexture\fP (const std::string &file)"
.br
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTexture\fP &texture) const noexcept"
.br
.ti -1c
.RI "void \fBset_texture\fP (const std::string &file, bool enable_mipmap=true)"
.br
.ti -1c
.RI "GET std::string \fBget_file\fP () const noexcept"
.br
.ti -1c
.RI "GET bool \fBexists\fP () const noexcept"
.br
.ti -1c
.RI "GET bool \fBis_opaque\fP () const noexcept"
.br
.ti -1c
.RI "GET const DirectX::ScratchImage & \fBget_image\fP () const noexcept"
.br
.ti -1c
.RI "GET const DirectX::ScratchImage & \fBget_mip_chain\fP () const noexcept"
.br
.in -1c

Public Member Functions inherited from \fBGraphicsTracker\fP
.in +1c
.ti -1c
.RI "bool \fBhas_changed\fP () const noexcept"
.br
.ti -1c
.RI "void \fBhas_changed\fP (bool changed) noexcept"
.br
.ti -1c
.RI "bool \fBneeds_compile\fP () const noexcept"
.br
.ti -1c
.RI "void \fBneeds_compile\fP (bool compile) noexcept"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBload_texture\fP (const std::string &file, DirectX::ScratchImage &image, DirectX::ScratchImage &mip_chain, bool enable_mipmap=true)"
.br
.RI "Compile texture file\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBGraphicsTracker\fP
.in +1c
.ti -1c
.RI "bool \fBchanged\fP {false}"
.br
.ti -1c
.RI "bool \fBcompile\fP {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTexture\fP for rendering onto objects\&. 


.PP
\fBSee also\fP
.RS 4
\fBShaderResourceView\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Texture::load_texture (const std::string & file, DirectX::ScratchImage & image, DirectX::ScratchImage & mip_chain, bool enable_mipmap = \fCtrue\fP)\fC [static]\fP"

.PP
Compile texture file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP Location of file\&. 
.br
\fIimage\fP The image data to write to\&. 
.br
\fImip_chain\fP The mipmap data to write to\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
