.TH "THROW_PARAMS" 3 "Thu Feb 8 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
THROW_PARAMS \- Throw information for a HPEW catch\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Throw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HRESULT \fBhr\fP"
.br
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.ti -1c
.RI "std::string \fBfunction_that_threw\fP"
.br
.ti -1c
.RI "std::string \fBfunc_location\fP"
.br
.ti -1c
.RI "std::string \fBfile_location\fP"
.br
.ti -1c
.RI "long \fBline_location\fP"
.br
.ti -1c
.RI "std::string \fBextra_message\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Throw information for a HPEW catch\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
