.TH "Triangle" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Triangle
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator SimpleTriangle\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVertex\fP \fBfirst\fP"
.br
.ti -1c
.RI "\fBVertex\fP \fBsecond\fP"
.br
.ti -1c
.RI "\fBVertex\fP \fBthird\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
