.TH "TVector3<>" 3 "Wed Apr 3 2024" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TVector3<>
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTVector3\fP (const \fBTVector3\fP &vector)"
.br
.ti -1c
.RI "constexpr \fBTVector3\fP (T x, T y, T z)"
.br
.ti -1c
.RI "bool \fBis_zero\fP () const noexcept"
.br
.ti -1c
.RI "\fBTVector3\fP< T > \fBoperator+\fP (\fBTVector3\fP< T > vector)"
.br
.ti -1c
.RI "\fBTVector3\fP< T > \fBoperator\-\fP (const \fBTVector3\fP< T > &vector) noexcept"
.br
.ti -1c
.RI "\fBTVector3\fP< T > \fBoperator*\fP (const \fBTVector3\fP< T > &vector) const noexcept"
.br
.ti -1c
.RI "\fBTVector3\fP< T > \fBoperator*\fP (T n) const noexcept"
.br
.ti -1c
.RI "\fBTVector3\fP< T > \fBoperator/\fP (const \fBTVector3\fP< T > &vector) const noexcept"
.br
.ti -1c
.RI "\fBTVector3\fP< T > \fBoperator/\fP (T n) const noexcept"
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBTVector3\fP< T > &vector) noexcept"
.br
.ti -1c
.RI "void \fBoperator\-=\fP (const \fBTVector3\fP< T > &vector) noexcept"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBTVector3\fP< T > &vector) const noexcept"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBTVector3\fP< T > &vector) const noexcept"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBTVector3\fP< T > &vector) noexcept"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (UCHAR index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP = 0"
.br
.ti -1c
.RI "T \fBy\fP = 0"
.br
.ti -1c
.RI "T \fBz\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
