.TH "VSD3DStarter::MeshExtents" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSD3DStarter::MeshExtents
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBCenterX\fP"
.br
.ti -1c
.RI "float \fBCenterY\fP"
.br
.ti -1c
.RI "float \fBCenterZ\fP"
.br
.ti -1c
.RI "float \fBRadius\fP"
.br
.ti -1c
.RI "float \fBMinX\fP"
.br
.ti -1c
.RI "float \fBMinY\fP"
.br
.ti -1c
.RI "float \fBMinZ\fP"
.br
.ti -1c
.RI "float \fBMaxX\fP"
.br
.ti -1c
.RI "float \fBMaxY\fP"
.br
.ti -1c
.RI "float \fBMaxZ\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
