.TH "VSD3DStarter::Bone" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSD3DStarter::Bone
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBParentIndex\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBInvBindPos\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBBindPos\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBLocalTransform\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
