.TH "VSD3DStarter::Keyframe" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSD3DStarter::Keyframe
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBBoneIndex\fP"
.br
.ti -1c
.RI "float \fBTime\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBTransform\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
