.TH "VSD3DStarter::Material" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSD3DStarter::Material
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DirectX::XMFLOAT4 \fBAmbient\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4 \fBDiffuse\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4 \fBSpecular\fP"
.br
.ti -1c
.RI "float \fBSpecularPower\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4 \fBEmissive\fP"
.br
.ti -1c
.RI "DirectX::XMFLOAT4X4 \fBUVTransform\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
