.TH "VSD3DStarter::SubMesh" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSD3DStarter::SubMesh
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBMaterialIndex\fP"
.br
.ti -1c
.RI "uint32_t \fBIndexBufferIndex\fP"
.br
.ti -1c
.RI "uint32_t \fBVertexBufferIndex\fP"
.br
.ti -1c
.RI "uint32_t \fBStartIndex\fP"
.br
.ti -1c
.RI "uint32_t \fBPrimCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
