.TH "VSD3DStarter::SkinningVertex" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VSD3DStarter::SkinningVertex
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBboneIndex\fP [NUM_BONE_INFLUENCES]"
.br
.ti -1c
.RI "float \fBboneWeight\fP [NUM_BONE_INFLUENCES]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
