.TH "Window" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window \- The main window for rendering\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Window\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (HINSTANCE hInstance)"
.br
.ti -1c
.RI "\fBWindow\fP (HINSTANCE hInstance, \fBRenderer\fP *graphics_scene)"
.br
.ti -1c
.RI "\fBWindow\fP (\fBRenderer\fP *renderer)"
.br
.ti -1c
.RI "void \fBset_up_window\fP (const \fBVector2\fP &position=\fBVector2\fP(CW_USEDEFAULT, CW_USEDEFAULT), const \fBVector2\fP &size=\fBVector2\fP(1200, 800), std::string name='Epic \fBWindow\fP :coolglasses:', DWORD style=WS_OVERLAPPEDWINDOW|WS_VISIBLE, const HWND &parent=NULL, DWORD extended_style=NULL, HMENU menu=NULL, void *lpParam=NULL)"
.br
.RI "Creates and sets up the window\&. "
.ti -1c
.RI "void \fBcheck_input\fP ()"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "GET HWND & \fBget_window\fP () noexcept"
.br
.ti -1c
.RI "GET HDC & \fBget_dc\fP () noexcept"
.br
.ti -1c
.RI "GET WNDCLASSEXA & \fBget_class\fP () noexcept"
.br
.ti -1c
.RI "GET \fBUVector2\fP \fBget_size\fP () const noexcept"
.br
.ti -1c
.RI "void \fBset_size\fP (const \fBUVector2\fP &size) noexcept"
.br
.ti -1c
.RI "GET bool \fBis_running\fP () const noexcept"
.br
.ti -1c
.RI "void \fBis_running\fP (bool running) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRenderer\fP * \fBgraphics_scene\fP = nullptr"
.br
.ti -1c
.RI "\fBEditorGUI\fP \fBeditor_gui\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main window for rendering\&. 


.PP
\fBSee also\fP
.RS 4
\fBGraphicsScene\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Window::set_up_window (const \fBVector2\fP & position = \fC\fBVector2\fP(CW_USEDEFAULT, CW_USEDEFAULT)\fP, const \fBVector2\fP & size = \fC\fBVector2\fP(1200, 800)\fP, std::string name = \fC'Epic \fBWindow\fP :coolglasses:'\fP, DWORD style = \fCWS_OVERLAPPEDWINDOW | WS_VISIBLE\fP, const HWND & parent = \fCNULL\fP, DWORD extended_style = \fCNULL\fP, HMENU menu = \fCNULL\fP, void * lpParam = \fCNULL\fP)"

.PP
Creates and sets up the window\&. 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP Initial position of window\&. 
.br
\fIsize\fP Initial size of window\&. 
.br
\fIname\fP \fBWindow\fP title\&. 
.br
\fIstyle\fP \fBWindow\fP styles\&. 
.br
\fIparent\fP Parent window\&. 
.br
\fIextended_style\fP More specific window styles\&. 
.br
\fImenu\fP \fBWindow\fP menu\&. Usually unneeded\&. 
.br
\fIlpParam\fP Unneeded\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
