.TH "World" 3 "Wed Jul 9 2025" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World \- The entire world\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <World\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcompile\fP ()"
.br
.ti -1c
.RI "void \fBclean_up\fP ()"
.br
.ti -1c
.RI "void \fBtick\fP (float dt)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBScene\fP >::iterator \fBactive_scene\fP"
.br
.ti -1c
.RI "std::list< \fBScene\fP > \fBscenes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The entire world\&. 

Stores scenes\&. 
.PP
\fBSee also\fP
.RS 4
\fBScene\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
