.TH "XMA2WAVEFORMATEX" 3 "Fri Aug 11 2023" "Liquid Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XMA2WAVEFORMATEX
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WAVEFORMATEX \fBwfx\fP"
.br
.ti -1c
.RI "WORD \fBNumStreams\fP"
.br
.ti -1c
.RI "DWORD \fBChannelMask\fP"
.br
.ti -1c
.RI "DWORD \fBSamplesEncoded\fP"
.br
.ti -1c
.RI "DWORD \fBBytesPerBlock\fP"
.br
.ti -1c
.RI "DWORD \fBPlayBegin\fP"
.br
.ti -1c
.RI "DWORD \fBPlayLength\fP"
.br
.ti -1c
.RI "DWORD \fBLoopBegin\fP"
.br
.ti -1c
.RI "DWORD \fBLoopLength\fP"
.br
.ti -1c
.RI "BYTE \fBLoopCount\fP"
.br
.ti -1c
.RI "BYTE \fBEncoderVersion\fP"
.br
.ti -1c
.RI "WORD \fBBlockCount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Liquid Engine from the source code\&.
